### ISSUE TITLE
Mesh generation with overlapping geometries

### ISSUE THREAD

**Issue by Agent6-6-6** [robbievanleeuwen/section-properties#10]
**Describe the bug**
Hi Robbie

I've been playing around with how merging sections works and noted a few odd things happening that may either be bugs or simply limitations in the code or the way geometry can be merged that might need further investigation or at a the very least some additional coverage in the documentation if these are limitations.

Merging two geometries where they are touching or overlapping has mixed effects on the mesh generated. API documentation seems to only briefly discuss/note that overlapping geometries can be merged and cleaning the geometry will attempt to fix any issues with the mesh. I have noted in testing some scenarios that the mesh seems to be created but seems to bug out a bit and assume this is not intended!

Consider the following 4 scenarios which might cover practical use cases for generating merged sections to demonstrate the varying results in the mesh being generated:-

1. If the two geometries just touch, and no closed regions are created the mesh seems to be generated as intended. Assuming this is the intended behaviour.
![Figure_1](https://user-images.githubusercontent.com/36808164/57169064-c141c080-6e58-11e9-91d5-e09305aed1ce.png)
2. If the two geometries just overlap, say one goes into the other by 5mm, the mesh seems to be created ok, with facets on the lines of overlap. Assuming this is the intended behaviour. Though see point on the control point in 3 below as may also trigger incorrect mesh if control point is in the overlap region.
![Figure_2](https://user-images.githubusercontent.com/36808164/57169302-fa2e6500-6e59-11e9-85c7-e67a9c2e29fc.png)
3. If the two geometries fully overlap such that part of the geometry completely crosses the other, the mesh seems to bug out as shown in this screenshot. Assuming either this is a bug or simply not possible to generate geometry like this. In practice you might use this method to model plates on either side of a central plate to simply generating the model. But might need to be split into another geometry for each projection, or add documentation around this limitation? I am assuming its something to do with there being no control point within one 'part' of the section as the mesh seems ok within the regions with the control point specified (similar to what was discussed in #1)
![Figure_3](https://user-images.githubusercontent.com/36808164/57169111-01a13e80-6e59-11e9-898d-90f82b72e195.png)
4. If the two geometries are merged such that a closed internal 'hole' is created, again the meshing seems to bug out and takes the closed region as being solid. There does not seem to be any way to account for the hole being a hole. Again the mesh seems to bug out with a larger mesh in the hole region. I assume this is not intended, nor does there seem to be any practical way to join predefined sections with the formation of a hole and get the code to treat it as a hole. I assume in this case the only way to do it would be to generate the whole thing as one custom section and define the hole? Or is there something I'm missing here to get it working as intended?
![Figure_4](https://user-images.githubusercontent.com/36808164/57169175-5e9cf480-6e59-11e9-95c8-9e7f4cc2b8e5.png)

**To Reproduce**
Run the code below to demonstrate all 4 scenarios:
```
import sectionproperties.pre.sections as sections
from sectionproperties.analysis.cross_section import CrossSection

# Scenario 1 - just touching, assume this is intended behaviour regarding meshing
geometry1 = sections.AngleSection(d=150, b=100, t=8, r_r=12, r_t=5, n_r=16, shift=[230, 200])
geometry1.rotate_section(angle=180, rot_point=[230, 200])
geometry2 = sections.ISection(d=250, b=250, t_f=20, t_w=10, r=10, n_r=10)
geometry = sections.MergedSection([geometry1, geometry2])
geometry.clean_geometry(verbose=True)
mesh = geometry.create_mesh(mesh_sizes=[5, 5])
section = CrossSection(geometry, mesh)
section.display_mesh_info()
section.plot_mesh()

# Scenario 2 - slightly overlapping, assume this is the intended behaviour (provided control point is not in the overlapped region)
geometry1 = sections.AngleSection(d=150, b=100, t=8, r_r=12, r_t=5, n_r=16, shift=[223, 200])
geometry1.rotate_section(angle=180, rot_point=[223, 200])
geometry2 = sections.ISection(d=250, b=250, t_f=20, t_w=10, r=10, n_r=10)
geometry = sections.MergedSection([geometry1, geometry2])
geometry.clean_geometry(verbose=True)
mesh = geometry.create_mesh(mesh_sizes=[5, 5])
section = CrossSection(geometry, mesh)
section.display_mesh_info()
section.plot_mesh()

# Scenario 3 - two geometries completely overlapping, mesh only generated correctly within the regions with the control points?
geometry1 = sections.AngleSection(d=150, b=100, t=8, r_r=12, r_t=5, n_r=16, shift=[150, 200])
geometry1.rotate_section(angle=180, rot_point=[150, 200])
geometry2 = sections.ISection(d=250, b=250, t_f=20, t_w=10, r=10, n_r=10)
geometry = sections.MergedSection([geometry1, geometry2])
geometry.clean_geometry(verbose=True)
mesh = geometry.create_mesh(mesh_sizes=[5, 5])
section = CrossSection(geometry, mesh)
section.display_mesh_info()
section.plot_mesh()

# Scenario 4 - just touching but formation of a closed region, as no way to recognise the formation of the 'hole'?
geometry1 = sections.AngleSection(d=150, b=100, t=8, r_r=12, r_t=5, n_r=16, shift=[230, 170])
geometry1.rotate_section(angle=180, rot_point=[230, 170])
geometry2 = sections.ISection(d=250, b=250, t_f=20, t_w=10, r=10, n_r=10)
geometry = sections.MergedSection([geometry1, geometry2])
geometry.clean_geometry(verbose=True)
mesh = geometry.create_mesh(mesh_sizes=[5, 5])
section = CrossSection(geometry, mesh)
section.display_mesh_info()
section.plot_mesh()
```

**Expected behavior**
Some way of accounting for these scenarios without having to resort to defining custom sections (in the case of scenario 4) or more geometry elements (in the case of scenario 3)?

Or outline any limitations in the geometry merging method in the documentation?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version - latest master commit 90f8ffb485c631a0e497ae3d86a682316e0747b7

Many thanks!

**Comment by robbievanleeuwen** [comment]
Hi Agent6-6-6,

Thanks for looking into this. I am really at the mercy of the meshing algorithm I chose to implement when it comes to mesh generation as this is a topic that is pretty well outside of my area of knowledge. Having said that, [triangle](https://www.cs.cmu.edu/~quake/triangle.html) is an excellent mesh generation tool and I am probably (almost definitely) not fully utilising its potential!

Regarding the above examples:

1. Yes this is the intended behaviour.
2. I wouldn't recommend having overlapping regions, although in most cases things work out ok like in this example.
3. This highlights one of the issues when trying to mesh overlapping regions. You're right that you get an issue with the control points. You can try to get around this by manually adding additional control points and mesh sizes to the final geometry object but this is a bit of a hack. I would recommend modelling each region so there are no overlaps, although this may be a bit more effort in some cases.
4. Correct, if you create a closed region the default response of the meshing algorithm will be to fill in this hole with elements. An easy workaround is to manually add a hole: `geometry.add_hole([200, 100])` - you can see this in action in the example below. Although there may be some way to program a way of detecting this issue, for me at least, this is a problem that is beyond my expertise when you consider that arbitrary sections can be formed from merging an infinite number of arbitrary sub-sections. I would advise the user to check the mesh and add holes as required.

Here's a bonus fifth scenario building on scenario four - a welded angle to i-section with variables for weld size and section separation:

```python
import copy
import sectionproperties.pre.sections as sections
from sectionproperties.analysis.cross_section import CrossSection

# Scenario 5 - angle welded to I-section
weld_length = 6
gap = 1

# create angle and isection
angle = sections.AngleSection(d=150, b=100, t=8, r_r=12, r_t=5, n_r=16, shift=[230 - gap, 170 - gap])
angle.rotate_section(angle=180, rot_point=[230, 170])
isection = sections.ISection(d=250, b=250, t_f=20, t_w=10, r=10, n_r=10)

# create two welds at the origin
weld1 = sections.CustomSection(
	points=[[0,0], [weld_length, 0], [0, weld_length]],
	facets=[[0,1], [1,2], [2,0]],
	holes=[],
	control_points=[[weld_length / 3, weld_length / 3]]
)
weld2 = copy.deepcopy(weld1)

# assign a shift to the first weld and shift to the new lcoation
weld1.shift = [130, 170 + gap]
weld1.shift_section()

# assign a shift to the second weld and shift to the new lcoation
weld2.shift = [230 + gap, 20]
weld2.shift_section()

geometry = sections.MergedSection([angle, isection, weld1, weld2])
geometry.clean_geometry(verbose=True)
geometry.add_hole([200, 100])
geometry.plot_geometry()

mesh = geometry.create_mesh(mesh_sizes=[5, 5, 1, 1])
section = CrossSection(geometry, mesh)
section.display_mesh_info()
section.plot_mesh()
```

![weld](https://user-images.githubusercontent.com/18841910/57224616-61603b00-704d-11e9-9d80-449f8089f2bd.png)

**Comment by robbievanleeuwen** [comment]
Actions:

- Add further documentation to meshing section making the above issues clear.

**Comment by Agent6-6-6** [comment]
Yeah makes sense that if you are doing something unique that you need to review the input mesh and deal with any complexities. I guess if you had a use case to repeatedly creating a merged section like this using some user code leveraging your code then you are going to know for a particular section where the hole is and can deal with it without end user intervention. But agree for any arbitrary sections being combined the possibilities are endless, hence reviewing the mesh is very important!

Thinking out aloud (i.e. not knowing any of the limitations/complexities of the meshing routines), I wonder if there is a way to address the overlapping sections via creating the mesh when sections are not overlapping, and then shifting the mesh and doing some cleaning of the mesh in or near overlapping regions. 

In the interim a workaround for scenario 3 is achievable by adding additional control points within the regions where the mesh is not being correctly generated applied (didn't realise you could add extra control points or holes after like this!). Code treats this as another region and needs another entry in the `geometry.create_mesh()` routine as a result to cover the mesh size in the new region past the overlap. 
```
# Scenario 3 - two geometries completely overlapping, mesh only generated correctly within the regions with the control points?
geometry1 = sections.AngleSection(d=150, b=100, t=8, r_r=12, r_t=5, n_r=16, shift=[150, 200])
geometry1.add_control_point(control_point=[245, 205])
geometry1.plot_geometry()
geometry1.rotate_section(angle=180, rot_point=[150, 200])

b = 250
d = 250
t_f = 20
geometry2 = sections.ISection(d=d, b=b, t_f=t_f, t_w=10, r=10, n_r=10)
geometry2.add_control_point(control_point=[b / 2, d - t_f])
geometry = sections.MergedSection([geometry1, geometry2])
geometry.clean_geometry(verbose=True)
mesh = geometry.create_mesh(mesh_sizes=[5, 5, 5, 5])
section = CrossSection(geometry, mesh)
section.display_mesh_info()
section.plot_mesh()
```
Resulting mesh:-
![Figure_1](https://user-images.githubusercontent.com/36808164/57251501-16224880-709e-11e9-9397-ffdcc1db8aea.png)

This got me thinking if there is a way to recognise any valid regions of the merged/overlapping section where the generated mesh is larger than a defined mesh size, in a way detecting where the mesh has gone haywire. In a way as a catchall to try pickup on these types of issues, whereby if a region does not have a mesh size applied (and hence no control point) that it just defaults to using a default mesh size. 

Unsure but if there was a way to detect if the area of mesh anywhere in the merged sections is greater than the max of all the mesh sizes defined in `geometry.create_mesh()` for the initial regions, then add an arbitrary extra control point at the centroid of one of these mesh triangles, regenerate the mesh, check again looping until all orphaned regions have had the fall back default mesh size applied and extra terms are added to `geometry.create_mesh()` to match the new number of regions being defined by added control points. Default could be taken as the max value specified initially within `geometry.create_mesh()` for all terms to get some level of consistent mesh size throughout. Just a thought anyway, no idea if this is even viable approach to clean the mesh in a hacky way via an iterative approach to pickup on poorly defined merged sections.

I note as well in the documentation there is possibly an error under the `add_control_point()` docs, where it references `hole` instead of `control point`?
![Capture](https://user-images.githubusercontent.com/36808164/57249576-6b0f9000-7099-11e9-85c8-017cd48e146e.PNG)

Your example with the welds raises a question in my mind about the validity of some of the merged sections examples you give when you have two flat surfaces in contact, especially if the bits being added are only in contact with gap (however small) and connecting welds vs being fully composite and bonded together over the full contact surface. For example in reality the following section taken from your examples is likely connected via discrete welds, vs being one solid section like an extruded section, intuitively as a result it seems to me that any stress analysis and some properties may not in fact be valid unless they are separated by some gap and connected at discrete points to represent the actual connection (perhaps should be raised in passing in the docs, as its not something you need to solve, but something for users to consider I guess depending on their individual use case). 
![Figure_1](https://user-images.githubusercontent.com/36808164/57252263-dbb9ab00-709f-11e9-8c30-439af616980c.png)

**Comment by Agent6-6-6** [comment]
Hi Robbie

I've been working on another project where I am using the [shapely ](https://shapely.readthedocs.io/en/latest/)package for all the geometrical operations I require. This package has tests for reporting a random point inside a closed polygon, merging geopmetry and finding the intersections and 101 things. 

I could see it being useful for taking your defined geometry coordinates, merging all of them to create all the possible intersections and resultant polygons. Then testing if the resulting polygons were within the original section geometry (to define if it was an original or formed 'hole' or if it was originally part of some 'section'). This would allow definition of any new voids inadvertently formed and being treated as the section, and allow for adding new control points in parts of the section that have due to the merging process been orphaned with no control point/mesh size or which turned into a void.

This would be one way of getting rid of the control points being user specified (and the inherent errors that can result in this process!).

Just thought I'd mention it, as I've been playing around with the shapely package for a month or so and it seems like a good way to preprocess the geometry/coordinates you are dealing with before merging, and it would definately be able to address some of the limitations that were noted in the above posts within a few loops. Someone else has done the hard work regarding all the required geometrical manipulations.

Thanks!

**Comment by robbievanleeuwen** [comment]
Hi Agent,

Have had a look through the shapely package and it looks awesome! Wish I'd knew about this a few years ago! A lot of your suggestions are valid and worthwhile additions; however, at the moment, I don't have the time to overhaul the pre-processing package to incorporate shapely in a useful way. In the meantime I'll endeavour to make the few documentation changes listed earlier.

Robbie

**Comment by Vinythewheel** [comment]
Hi rob,
I spend couple of houre on your amazing function. I start to implement a piece of code to load DXF file. I add "def draw_arc(self, pt, r, start_angle,end_angle, n=5):" and "class ImportDXF(Geometry):"
to section.py definition.

[sections.zip](https://github.com/robbievanleeuwen/section-properties/files/4672754/sections.zip)

It work good for some part but just fail on other. I can explaine why. Did you have any idea?
I join the non meshable dxf file...
I probably miss somthing simple.

**Comment by MZecchetto** [comment]
Dear @Vinythewheel,
I gave a look at your code and I think the problem is the object coordinate system of the ARCs. You are assuming that it coincides with the World one, but it is not true. Not always, at least. 
If you calculate the points in the ocs and then you convert in the wcs, it works.
![second_test](https://user-images.githubusercontent.com/50821222/95739396-15c2af80-0c8b-11eb-9343-19932547e648.png)
@robbievanleeuwen I developed a bit the code by @Vinythewheel and now it is possible to read automatically holes and control points directly from a *.dxf file.
![test_circle](https://user-images.githubusercontent.com/50821222/95739551-4dc9f280-0c8b-11eb-9f21-e1d679ef1ac1.png)
![third_test](https://user-images.githubusercontent.com/50821222/95739558-502c4c80-0c8b-11eb-8aa5-aec0adc698a3.png)
To be honest, the managing of the ARC entities is not as robust as I would, but I think, as it is, it's a good starting point.
If you allow me, I would push a draft PR so you can check what I've done and we can discuss all the implementation details.
With best regards,

Massimiliano

**Comment by robbievanleeuwen** [comment]
Hi @MZecchetto,

Happy to have a look at this, would be a great addition to the package.

Thanks,
Robbie

**Comment by MZecchetto** [comment]
@robbievanleeuwen I am having troubles when pushing my branch.
![image](https://user-images.githubusercontent.com/50821222/95749378-c638af80-0c9b-11eb-8bad-b5171f59eb14.png)
Do I need your permission?

**Comment by ebrahimraeyat** [comment]
> @robbievanleeuwen I am having troubles when pushing my branch.
> ![image](https://user-images.githubusercontent.com/50821222/95749378-c638af80-0c9b-11eb-8bad-b5171f59eb14.png)
> Do I need your permission?

Hi @MZecchetto, you must fork it on your GitHub and then when you pushed changes to your GitHub, create a PR for @robbievanleeuwen.

**Comment by MZecchetto** [comment]
@ebrahimraeyat I did in this way in fact. 
I did several PRs in Linux and I never encountered issues. Now I switched to W10 and I am missing something...
![image](https://user-images.githubusercontent.com/50821222/95782736-a96a9f00-0cd0-11eb-8505-933db8c9d8a9.png)
any clue?

**Comment by Vinythewheel** [comment]
Ok, never work with github. All on my own pc and working. Can you tell me what us PR?

Génilec inc.

Vincent Leroux Ing.

2711 Lyall, Montréal, Qc

H1N 3G8

(514)794-2010

vleroux@genilec.com

________________________________

**Comment by MZecchetto** [comment]
@Vinythewheel I will do another test tomorrow in Linux, let's see if I will be able to push the branch. In the screenshot above I did another test with a local branch called "ImportDXF" and just one commit "commit_test"

**Comment by MZecchetto** [comment]
@Vinythewheel PR means Pull Request, if this was your question

**Comment by robbievanleeuwen** [comment]
Hi @MZecchetto,

Have worked with a number of pull requests in the past so I don't think it's a permissions issue. It looks like you are using the github desktop program (?), I haven't used this before and just use the terminal (on mac) and the website interface. Maybe you could try using the web interface, I found [this](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) article helpful when doing a pull request on another project.

Good luck :)

Robbie

**Comment by robbievanleeuwen** [comment]
Also it may be because you are trying to do a draft PR? I only have a free account so it may not work:

`Draft pull requests are available in public repositories with GitHub Free for organizations and legacy per-repository billing plans, and in public and private repositories with GitHub Team and GitHub Enterprise Cloud. For more information, see "GitHub's products."`
