### ISSUE TITLE
Minor documentation error?

### ISSUE THREAD

**Issue by Agent6-6-6** [robbievanleeuwen/section-properties#11]
**Describe the bug**
This highlighted notation is possibly wrong in the documents, based on the form of the other notations, believe it should actually be sigma_zx, Vy?? (in `get_stress()`)
![image](https://user-images.githubusercontent.com/36808164/57260354-4aeec980-70b7-11e9-9e8d-ddbb3c40bb16.png)

**Comment by robbievanleeuwen** [comment]
Good pickup! Will be included in the next commit.
