### ISSUE TITLE
Composite sections with dissimilar materials causes incorrect results

### ISSUE THREAD

**Issue by connorferster** [robbievanleeuwen/section-properties#111]
**Describe the bug**
When applying forces to a composite section with dissimilar materials, apparently erroneous stress are calculated. I am not sure yet what is causing this. The input geometry into the mesh seems fully correct and the mesh seems to also be correct. However, when an axial force is applied, the results are obviously incorrect. This does not happen when a single material is applied to both sections. 

**To Reproduce**
See below gist:
https://gist.github.com/connorferster/6cbb131fe1b26124aae24d3e61bec980

**Expected behaviour**
Applied axial load should create a uniform stress corresponding to each material.

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - Version 93.0

@robbievanleeuwen, have you seen this sort of thing before in your earlier development?

**Comment by connorferster** [comment]
@ccaprani Turns out that my conda environments got entirely messed up. I created a new environment and did a fresh install and everything turned out fine. I could not reproduce in the new environment.

**Comment by ccaprani** [comment]
@connorferster that is good news indeed. In spite of the "no warranty", super-important to ensure this is running bug-free.
