### ISSUE TITLE
Reading STL file with the section

### ISSUE THREAD

**Issue by spolanski** [robbievanleeuwen/section-properties#123]
Hello,

Thanks for such great code! Is there a way to load a 2D mesh directly into section-properties? For example, I have got an STL file that I would like to use to evaluate properties. I think it might be more related to MeshPy rather than section-properties, but maybe you know the way to do it

Thanks!

**Comment by brendanhorne** [comment]
I'm not sure about STL but I have been somewhat successful loading in a gmsh file using https://github.com/inducer/gmsh_interop with some slight modifications.

**Comment by robbievanleeuwen** [comment]
Hi @spolanski 

This is not implemented at this time, sectionproperties has specific requirements for the mesh type (e.g. Tri6 elements) so the meshing is done in-house.

Robbie
