### ISSUE TITLE
Plot figure size not adjusting well

### ISSUE THREAD

**Issue by robbievanleeuwen** [robbievanleeuwen/section-properties#126]
**Describe the bug**
In v1, the figure size adjusted quite well to the plot contents. Plotting figures now either cuts off numbers/labels or is too large.

**To Reproduce**
Centroid & stress plots from examples under 'Running an Analysis' docs.

**Expected behaviour**
In v1 plot figure size was adjusted to fit the size of plot with minimal white space and no clipping.

**Screenshots**

<img src="https://user-images.githubusercontent.com/18841910/146296149-b9fb3fbe-c19a-438a-8be8-80f92f917fea.png" width="600" />
<img src="https://user-images.githubusercontent.com/18841910/146296155-38d77a97-840e-4aec-aee9-8a1cf1de27e0.png" width="600" />
<img src="https://user-images.githubusercontent.com/18841910/146296159-bf849ce5-81f6-49bc-a27a-24e95f99c22c.png" width="600" />

**Desktop (please complete the following information):**
 - OS: mac
 - python: 3.8

**Comment by connorferster** [comment]
The plots are something that I would like to fine tune, too. By adding the ability to change the size, the user also has to select an appropriate dpi and fiddling with my two "knobs" makes it harder. I am certainly open to suggestions for improvement!

**Comment by robbievanleeuwen** [comment]
@connorferster quick one - was there a reason you removed the legend for `plot_geometry()` that displayed points/facets, control points & holes?

**Comment by connorferster** [comment]
Probably back in the day. But it would have been a bad reason. I was wondering yesterday why I removed it!

**Comment by robbievanleeuwen** [comment]
Fixed in #138.
