### ISSUE TITLE
Shapely deprecations

### ISSUE THREAD

**Issue by connorferster** [robbievanleeuwen/section-properties#137]
Shapely v1.8.0 was released in preparation for shapely v2.0. The 1.8.0 release is for the purpose of notifying users of upcoming deprecations. These deprecations do not affect the pre-processor but it does affect the DXF importer and the Rhino importer (as can be seen when running the sectionproperties tests in pytest when you have shapely v1.8.0 installed).

To prevent sectionproperties v2 from displaying shapely deprecation warnings, these libraries need to be updated.

I have just made the required changes in cad_to_shapely and have submitted a PR to aegis1980 for review. If @normanrichardson is short on time, I will endeavor to submit a PR for the rhino_shapely_interop also.

**Comment by normanrichardson** [comment]
@connorferster any contributions there would be awesome. If you're feeling time-constrained, make an issue on the repo and I'll be happy to investigate and give a timeline estimate.

**Comment by normanrichardson** [comment]
@connorferster the changes have been released and are available in the latest version of [rhino_shapely_interop](https://pypi.org/project/rhino-shapley-interop/0.0.3/).

**Comment by connorferster** [comment]
Excellent!

**Comment by connorferster** [comment]
I think this is solved now, yeah?

**Comment by connorferster** [comment]
Will close now.
