### ISSUE TITLE
`.mirror_section()` is not mirroring section

### ISSUE THREAD

**Issue by connorferster** [robbievanleeuwen/section-properties#144]
**Describe the bug**
`.mirror_section()` only mirrors if a mirror point is given, not otherwise.

**To Reproduce**
Steps to reproduce the behaviour:
* Use `.mirror_section()` on any geometry without providing a mirror point

**Expected behaviour**
Mirror's section

**Comment by robbievanleeuwen** [comment]
Fixed in #145
