### ISSUE TITLE
License Change?

### ISSUE THREAD

**Issue by robbievanleeuwen** [robbievanleeuwen/section-properties#161]
Current MIT license may be too unrestrictive. What are your thoughts on what license sectionproperties should adopt?

**Comment by connorferster** [comment]
I am open to a conversation about this. 

My thoughts are generally as follows:

* I like the permissiveness of the MIT license. It makes sectionproperties officially Free Software.
* There are other permissive licenses which I would be happy with
* When it comes to commercial use, I see three general use cases:
   * Using the software in calculation scripts for solving individual problems
   * Using the software as part of a larger commercial software package for internal corporate use
   * Using the software as part of a larger commercial software package for re-sale
* Of those three commercial use cases, the one that gives the weird feeling to me is someone packaging up sectionproperties for re-sale
* A copy-left license would interfere with the last two (if not all three) commercial use cases
* WIth permissive licenses, commercial resale cannot be prevented but attribution can be controlled
* Commercial re-sale cannot generally be controlled without a dual-licensing scheme (most commonly done in conjunction with a copy-left license)
* I don't know if dual-licensing is worth it at this point

@nicolasdao describes the selection of an open source license as considering "what is it you are afraid of?" which I find to be a useful framing:
https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633

**Comment by robbievanleeuwen** [comment]
Thanks for the info @connorferster and doing the research for me :) I think with a bit more understanding I'm happy to stay with MIT.
