### ISSUE TITLE
GeometryCleaner altering small CustomSection and causing error in CrossSection initialisation

### ISSUE THREAD

**Issue by CoronelBuendia** [robbievanleeuwen/section-properties#17]
**Describe the bug**
When creating custom cross-sections, and carrying out a clean_geometry() step, as recommended, small cross-sections are failing upon initialisation.

**To Reproduce**

Minimum bug example below
```python
from sectionproperties.pre.sections import CustomSection
from sectionproperties.analysis.cross_section import CrossSection

def make_rectangle(width, height):
    points = [[-width/2, -height/2], [width/2, -height/2], [width/2, height/2],
              [-width/2, height/2]]
    facets = [[0, 1], [1, 2], [2,3], [3, 0]]
    return points, facets

def test_rectangle(width, height):
    points, facets = make_rectangle(width, height)

    geometry = CustomSection(points, facets, [], [[0, 0]])
    mesh_size = min([width, height])/2

    # This where the geometry is altered unexpectedly
    geometry.clean_geometry(verbose=True) 

    mesh = geometry.create_mesh([mesh_size])
    section = CrossSection(geometry, mesh)

for w, h in zip([100, 10, 1, 0.1, 0.01, 0.001], [200, 20, 2, 0.2, 0.02, 0.002]):
    print('width: ', w, 'height: ', h)
    test_rectangle(w, h)
```
The above example fails relatively cryptically when we get to a small-ish rectangle, see traceback below:
```python
width:  100 height:  200
width:  10 height:  20
width:  1 height:  2
width:  0.1 height:  0.2
width:  0.01 height:  0.02
Removed overlapping facets... Rebuilt with points: [0, 1]
Removed overlapping facets... Rebuilt with points: [1, 2]
Removed unused point 3
Traceback (most recent call last):

  File "<ipython-input-6-b7482b36466d>", line 21, in <module>
    test_rectangle(w, h)

  File "<ipython-input-6-b7482b36466d>", line 17, in test_rectangle
    section = CrossSection(geometry, mesh)

  File "C:\Anaconda3\lib\site-packages\sectionproperties\analysis\cross_section.py", line 210, in __init__
    init()

  File "C:\Anaconda3\lib\site-packages\sectionproperties\analysis\cross_section.py", line 117, in init
    elements[:, [3, 4, 5]] = elements[:, [5, 3, 4]]

IndexError: too many indices for array
```

**Expected behavior**
(The above error can be avoided by leaving out the `geometry.clean_geometry()` stage.)

I would expect the clean_geometry() stage to work correctly regardless of size (within reason). 

Solution ideas:
* Haven't looked in detail at GeometryCleaner, but perhaps this issue could be addressed by a tolerance calculated based on a characteristic length of the input geometry.
* Alternatively, if `clean_geometry` is not recommended for small cross-sections, then maybe an error or warning could be raised when a mesh has `len(elements) == 0` (as is the case following `clean_geometry()`, which causes the above `IndexError`).

**Desktop (please complete the following information):**
 - OS: Windows
- Python 3.6

**Additional context**

Stumbled across this repo when trying to calculate section properties myself. Ran a simple existing test battery to check FE cross-section properties with analytical values. In doing so, came across this issue.

Big thanks for all the good work, very helpful, will be using in future.

**Comment by Agent6-6-6** [comment]
Hi @CoronelBuendia 

I believe this is related to the same issue I noted in issue #15 which was solved by Robbie in the current master branch, see his comments in #15 

I believe it has not been packaged yet in a new version (assuming it will be in the next version), but if you download the master branch it has the fix required to get your code to run.

You code runs using the master branch with no errors with the following results:-

> width:  100 height:  200
width:  10 height:  20
width:  1 height:  2
width:  0.1 height:  0.2
width:  0.01 height:  0.02
width:  0.001 height:  0.002

**Comment by CoronelBuendia** [comment]
Hi @Agent6-6-6 

You are 100% right. Sorry I didn't check closed issues or the latest branch. (Forgot to mention I was operating just from the pip install).

Cheers!
