### ISSUE TITLE
Error with Matplot lib CenteredNorm

### ISSUE THREAD

**Issue by 301resa** [robbievanleeuwen/section-properties#177]
hi Thanks for your efforts - great work!

i tried the rhs [example](https://sectionproperties.readthedocs.io/en/latest/sphinx_gallery_examples/00-basic/06_stress.html#sphx-glr-sphinx-gallery-examples-00-basic-06-stress-py) however the code throughs out an error with the following message. 

  File "C:\Users\xyz\.spyder-py3\temp.py", line 22, in <module>
    from sectionproperties.analysis.section import Section

  File "C:\ProgramData\Anaconda3\lib\site-packages\sectionproperties\analysis\section.py", line 10, in <module>
    from matplotlib.colors import ListedColormap, CenteredNorm

ImportError: cannot import name 'CenteredNorm' from 'matplotlib.colors' (C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\colors.py)

i have python 3.8 and matplotlib 3.3.4

cheers,

**Comment by robbievanleeuwen** [comment]
Fixed with 70f0e99.
