### ISSUE TITLE
Principal stress equations in theory section don't show up

### ISSUE THREAD

**Issue by Spectre5** [robbievanleeuwen/section-properties#179]
**Describe the bug**
On the current readthedocs website for v2, the equations in the principal stresses do not show up correctly for me on both firefox and chromium:

![image](https://user-images.githubusercontent.com/31610422/150469077-1d6115c1-8fd5-48a8-95c5-1ea31468c7b2.png)

**Comment by robbievanleeuwen** [comment]
Thanks for picking this up @Spectre5, should be an easy fix :)

**Comment by robbievanleeuwen** [comment]
Fixed with 9f61946.

**Comment by robbievanleeuwen** [comment]
Not quite fixed yet...

**Comment by Spectre5** [comment]
Looks like those math environments have too many spaces at the start to me

**Comment by Spectre5** [comment]
Maybe that isn't it actually.  Probably an issue of some () that should be {} actually

**Comment by robbievanleeuwen** [comment]
Yep just popped out, will fix shortly 🤞

**Comment by robbievanleeuwen** [comment]
Fixed with 70f0e99.
