### ISSUE TITLE
Bridge Sections always returns Type 5

### ISSUE THREAD

**Issue by DougAJ4** [robbievanleeuwen/section-properties#182]
**Describe the bug**
With Rel 2.01 running from Windows, both section properties results and cross section plots are returned for section type 5, regardless of the section specified.

The code below seems to be the problem (lines 263 to 271):
    key = f"T{girder_type}"

    # Rather delicious code that assigns the values to the keys as variables
    for key, val in girder_dims.items():
        exec(key + "=val")

    d = girder_dims[key]["d"]
    t_b = girder_dims[key]["t_b"]
    t_w = girder_dims[key]["t_w"]

Changing the two lines below fixes the problem:
    # Rather delicious code that assigns the values to the keys as variables
    for key2, val in girder_dims.items():
        exec(key2 + "=val")

**Comment by robbievanleeuwen** [comment]
Thanks for the pickup @DougAJ4. Seems like these two lines were some rogue code, fixed with cac5647.

Will release v2.0.2 shortly to capture the recent fixes.

**Comment by robbievanleeuwen** [comment]
v2.0.2 now deployed on PyPI.

**Comment by DougAJ4** [comment]
v2.02 now installed and problem fixed.
