### ISSUE TITLE
Default plot size cutting off wider plot legends

### ISSUE THREAD

**Issue by Agent6-6-6** [robbievanleeuwen/section-properties#188]
@robbievanleeuwen this is potentially related to #159. But I've noticed with what appears to be a reduced default size of the plots from matplotlib that some portion of the legends on certain plots are disappearing off the edge of the default plot size. e.g.:-

![image](https://user-images.githubusercontent.com/36808164/152296206-0d062247-2fec-4296-8ce1-77d44a0ce83a.png)

Wondering if a default minimum plot size should be enforced by sectionproperties (or potentially some review and reformatting of the legends) to avoid this occurring in common cases with the default plot size (I could have sworn they were larger by default some time ago when I last used sectionproperties, which is what you've generally noticed under #159?). 

Mostly note it occurs on ```.plot_centroids()``` method where the legend is quite wide to start with.

Above example is running ```03_custom.py``` example on v3.5.1 of matplotlib with python 3.8.10.

I've seen a few examples with certain wider than height geometries cutting off much more of the legend. Generally if the returned figure is even marginally larger it seems to format better with the wider legends.

**Comment by robbievanleeuwen** [comment]
Hi @Agent6-6-6, sorry for the radio silence on this one. These plotting issues have genuinely stumped me, I'm not sure what I'm doing wrong but feel like it's a `matplotlib` issue. `tight_layout()` is supposed to fix this but they do say:

>tight_layout automatically adjusts subplot params so that the subplot(s) fits in to the figure area. This is an experimental feature and may not work for some cases. It only checks the extents of ticklabels, axis labels, and titles.

So probably an issue with the legends?

For now, I feel a bit defeated with trying to fix this one so would welcome any new & fresh ideas & PRs that look to fix this :pray:
