### ISSUE TITLE
What is the best way to create reinforced concrete geometry?

### ISSUE THREAD

**Issue by robbievanleeuwen** [robbievanleeuwen/section-properties#192]
Using the built-in `concrete_rectangular_section()` method, the geometry is generated using addition set operations. This can result in the following issue, where the `control_point` of the concrete coincides with the `control_point` of a steel bar:

```python
from sectionproperties.pre.pre import Material
import sectionproperties.pre.library.concrete_sections as conc_sec
from sectionproperties.analysis.section import Section

concrete = Material(
    name='Concrete', elastic_modulus=30.1e3, poissons_ratio=0.2, density=2.4e-6,
        yield_strength=32, color='lightgrey'
)
steel = Material(
    name='Steel', elastic_modulus=200e3, poissons_ratio=0.3, density=7.85e-6,
        yield_strength=500, color='grey'
)

geom = conc_sec.concrete_rectangular_section(
    b=1000,
    d=112,
    dia=12,
    n_bar=5,
    n_circle=16,
    cover=50,
    conc_mat=concrete,
    steel_mat=steel,
)

geom.plot_geometry()
geom.create_mesh(5)

sec = Section(geom)
sec.plot_mesh()
```
![Figure_1](https://user-images.githubusercontent.com/18841910/154388749-7c0903ed-1335-4550-bab5-e7c438919b58.png)
![Figure_2](https://user-images.githubusercontent.com/18841910/154388758-c03d090a-2c8e-449a-bf81-917b6bf282a6.png)
![Figure_3](https://user-images.githubusercontent.com/18841910/154388766-0e47dd6e-8219-47b9-bb1e-684c36108bfe.png)

While you get lucky with the material assignment, the mesh size of 5 is clearly not applied to the concrete region.

I thought doing a subtraction of the reinforcement from the concrete section then adding the reinforcement might work, but you are left with holes at the location of the reinforcement:

```python
from sectionproperties.pre.pre import Material
import sectionproperties.pre.library.concrete_sections as conc_sec
import sectionproperties.pre.library.primitive_sections as ps
from sectionproperties.analysis.section import Section

concrete = Material(
    name='Concrete', elastic_modulus=30.1e3, poissons_ratio=0.2, density=2.4e-6,
        yield_strength=32, color='lightgrey'
)
steel = Material(
    name='Steel', elastic_modulus=200e3, poissons_ratio=0.3, density=7.85e-6,
        yield_strength=500, color='grey'
)

b = 1000
d = 112

conc_geom = ps.rectangular_section(b=b, d=d, material=concrete)
reinf_geom = None

cover = 50
dia = 12
n_bar = 5
n_circle = 16

x_i = cover + dia / 2
spacing = (b - 2 * cover - dia) / (n_bar - 1)

for i in range(n_bar):
    bar = ps.circular_section(d=dia, n=n_circle, material=steel)
    bar = bar.shift_section(x_i + spacing * i, cover + dia / 2)

    conc_geom -= bar

    if i == 0:
        reinf_geom = bar
    else:
        reinf_geom += bar

conc_geom.plot_geometry()
reinf_geom.plot_geometry()
geom = conc_geom + reinf_geom
geom.plot_geometry()
```

![Figure_11](https://user-images.githubusercontent.com/18841910/154389986-215e59b8-4df5-412b-a663-41b594db6afe.png)
![Figure_12](https://user-images.githubusercontent.com/18841910/154389990-01e0298a-aa8b-47fa-b971-6794d226a514.png)

Not sure if this is the intended behaviour or if you think there is a better way of constructing this geometry? Obviously a bit of a edge case, but would be great to be able to handle this!

Keen to hear anyone's thoughts on this!

**Comment by Agent6-6-6** [comment]
What about a check on the final compound geometry to ensure that the control points for each concrete geometry do not fall within the bar geometries? 

Thinking aloud.... would this take the form of the representative point only for each individual concrete geometry actually being created based on a compound geometry created by concrete geometry minus every other individual bar geometry that lies within the concrete. Do this for every concrete geometry. This should create the control point outside of the bars to avoid this issue.  

I remember in the original shapely thread I had the same issue with overlapping geometries and creation of areas of section without the mesh being applied, I think @connorferster put it in the too hard basket, to be addressed later. But for concrete routine the above seems fairly easy to implement unless I'm oversimplifying it

**Comment by connorferster** [comment]
Looking at @robbievanleeuwen's example code, I am surprised the incremental add and subtract work because those methods have not been implemented in the Geometry class. Do those methods work and perform as expected?

Sorry have been radio silent: have been preparing, and am now giving, another 10-week Python course at the office.

Will take a look at things this weekend. Also have a practical modelling discussion I want to chat out with you all.

**Comment by robbievanleeuwen** [comment]
I'm open to a fix being concrete specific for now (or at least one level of nesting which is what you get with reo embedded in concrete) - this will at least be a hotfix for the concrete section library.

@connorferster I didn't realise they hadn't been implemented! Yes they appear to work as intended :)

**Comment by Czarified** [comment]
As an aside...

>  I am surprised the incremental add and subtract work because those methods have not been implemented in the Geometry class. Do those methods work and perform as expected?

I don't think you need to implement all the dunder_iter arithmetic methods. The default is to use the dunder_math methods. So `__iadd__` will just use the `__add__` method to self. [Link for reference.](https://docs.python.org/3/reference/datamodel.html#object.__iadd__)
