### ISSUE TITLE
Default plastic centroid bounds

### ISSUE THREAD

**Issue by Agent6-6-6** [robbievanleeuwen/section-properties#2]
**Describe the bug**
While experimenting I came across this situation where the code throws an error.

**To Reproduce**
Run this code
```
import sectionproperties.pre.sections as sections
from sectionproperties.analysis.cross_section import CrossSection

section_type = 'PFC'
d = 380
b = 100
t_f = 3
t_w = 3
r = 14
n_r = 50

mesh_area = 1  # wb.sheets[0].range('mesh_area').value
geometry = sections.PfcSection(d=d, b=b, t_f=t_f, t_w=t_w, r=r, n_r=n_r)

mesh = geometry.create_mesh(mesh_sizes=[mesh_area])
section = CrossSection(geometry, mesh)
section.calculate_geometric_properties()
section.calculate_plastic_properties()
section.calculate_warping_properties()
section.plot_mesh()
```
Error as follows
```
C:\Users\qqq>C:/Users/qqq/AppData/Local/Programs/Python/Python37/python.exe c:/Users/qqq/Downloads/SectionPropertiesTest/test.py
Traceback (most recent call last):
  File "C:\Users\qqq\AppData\Local\Programs\Python\Python37\lib\site-packages\sectionproperties\analysis\cross_section.py", line 754, in calc_plastic
    self, pc_region, verbose)
  File "C:\Users\qqq\AppData\Local\Programs\Python\Python37\lib\site-packages\sectionproperties\analysis\cross_section.py", line 1852, in calculate_plastic_properties
    np.array([0, 1]), fibres[0:2], 2, pc_region[0])
  File "C:\Users\qqq\AppData\Local\Programs\Python\Python37\lib\site-packages\sectionproperties\analysis\cross_section.py", line 2067, in pc_algorithm
    full_output=True, disp=False, xtol=1e-6, rtol=1e-6)
  File "C:\Users\qqq\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\optimize\zeros.py", line 754, in brentq
    r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)
ValueError: f(a) and f(b) must have different signs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/qqq/Downloads/SectionPropertiesTest/test.py", line 22, in <module>
    section.calculate_plastic_properties()
  File "C:\Users\qqq\AppData\Local\Programs\Python\Python37\lib\site-packages\sectionproperties\analysis\cross_section.py", line 765, in calculate_plastic_properties
    calc_plastic()
  File "C:\Users\qqq\AppData\Local\Programs\Python\Python37\lib\site-packages\sectionproperties\analysis\cross_section.py", line 758, in calc_plastic
    raise RuntimeError(str)
RuntimeError: Platic section properties calculation failed. Consider increasing pc_region bounds.

```
**Expected behavior**
Should run, I note if I change some of the inputs (t_w/b to larger values) the error no longer occurs and things run as expected, so it is potentially tied to certain values or conditions related to these?

Any ideas?

Note also in last runtime error plastic is spelt incorrectly :)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by robbievanleeuwen** [comment]
Thanks for pointing this out. I'll try to have a look at this (and your other comment) tonight or tomorrow.

Cheers,
Robbie

**Comment by robbievanleeuwen** [comment]
Hi Agent6-6-6,

In this case the error message was helpful (even if spelt incorrectly :sweat_smile:). From the docs for `pc_region`:

> Region of cross-section in which to search for the plastic centroids. The value represents the fraction of the depth to search within perpendicular to the axis being considered [x-axis, y-axis, 11-axis, 22-axis]. Ensure 0 < pc_region[i] < 1. The default scheme searches 95% of the section depth (ie. centroid ± 47.5%)

In the section you have defined the plastic centroid in the x-direction sits at x=2.377 mm which is _just_ outside the default 95% search area. I chose these default bounds as for a majority of sections this seemed to work, however maybe it is not always the case for thin-walled sections. Increasing these bounds may decrease the performance of the algorithm for more standard sections, however I would consider changing these default bounds if justified - do you have a suggestion on what these should be?

Here's the modified code that works (with some additional useful debugging info - note in the debugging output the plastic centroid location is relative to the elastic centroid):

```python
import sectionproperties.pre.sections as sections
from sectionproperties.analysis.cross_section import CrossSection

section_type = 'PFC'
d = 380
b = 100
t_f = 3
t_w = 3
r = 14
n_r = 50

mesh_area = 1  # wb.sheets[0].range('mesh_area').value
geometry = sections.PfcSection(d=d, b=b, t_f=t_f, t_w=t_w, r=r, n_r=n_r)

mesh = geometry.create_mesh(mesh_sizes=[mesh_area])
section = CrossSection(geometry, mesh)

section.calculate_geometric_properties()
section.calculate_plastic_properties(verbose=True, pc_region=[0.98, 0.98, 0.98, 0.98])

section.plot_centroids()
section.display_results()
```

Robbie

**Comment by Agent6-6-6** [comment]
Thanks for that, if it's using Brent's method then I would expect it to converge fairly fast (maybe one more iteration at most) if you had the bounds set to 0 to 1. Not sure how much calcs are going on at each iteration (suspect a lot depending on the mesh size and number of resultant triangular areas). 

But its something you could compare your defaults with full range and see via a script for various sections and see if it makes a meaningful difference. Certainly for some sections you can do some preliminary elimination/refinements of the range, for example for a built in symmetric tee section taking flange and web areas and comparing areas will tell you if the plastic neutral axis lies in one or the other to refine the search to just the web or the flange). My guess is if using Brent's method that you won't see a whole lot of difference, though I have not delved into your source code yet to see what's going on under the hood! 

If it takes an iteration or two more for more "exotic" sections or refined meshes it's not the end of the world as it takes a while anyway. From my personal perspective I'd rather receive an answer than an error even if it happened to take a little longer.

**Comment by robbievanleeuwen** [comment]
Hi Agent6-6-6,

Initially I thought it would be quite difficult to search over the entire depth, however turns out it wasn't hard at all! I have now updated the algorithm to search the entire depth and removed the pc_region variable altogether as it no longer relevant.

Closing this issue with commit acc3660.

Robbie
