### ISSUE TITLE
CompoundGeometry.from_points() work only is if nodes are serialised from node number 0

### ISSUE THREAD

**Issue by MarcoV10** [robbievanleeuwen/section-properties#205]
Not exactly a bug, but a clarification from the recent release. 

With the latest update CompoundGeometry.from_points() only works if the nodes are numbered starting in 0. this is due the reference to the list indexation:

In line 1216 from the file sectionproperties.pre.geometry.Geometry.from_points

points[i_idx] 

Will trigger an error if it follows the indexation that worked in the previous version, But if nodes are numbered from 0 (not from 1), the tasks runs ok

**Comment by robbievanleeuwen** [comment]
Thanks for pointing this out. Can you clarify a few things for me?

> With the latest update 

Are you referring to sectionproperties v1.0.x?

Could you also provide a short example that used to work for you that no longer works?

Cheers!

**Comment by MarcoV10** [comment]
Sure. Yes I refer to that change, I followed the reference in the previous version which contained an specific example. The previous example was:

points [[0, 0], [100, 0], [75, 50], [25, 50], [15, 10], [85, '11'], [70, 40], [30, 40]]
facets [[1, 2], [2, 3], [3, 4], [4, 1], [5, 6], [6, 7], [7, 8], [8, 5]]
control_points [[5.0, 5.0]]
holes [[50.0, 25.0]]

![image](https://user-images.githubusercontent.com/36434407/158547299-1c8ca746-9a6d-45f7-ae70-b008657ca877.png)

Now it can only works if facets are renumbered like
facets [[0, 1], [1, 2], [2, 3], [3, 0], [4, 5], [5, 6], [6, 7], [7, 4]]

I was getting the error "list index out of range" and I realised that was from the **points[i_idx]** command in the function, where a list is called up from 0, not from 1

**Comment by robbievanleeuwen** [comment]
Hi @MarcoV10, as far as I'm aware the facet list always followed python list conventions. That is, referencing the first point in the list as a facet would be a 0 (zero).

The docs for version ``1.0.8`` are [here](https://sectionproperties.readthedocs.io/en/1.0.8/rst/geom_mesh.html#arbitrary-cross-section-geometries) and the above example has point indices from 0 to 7 (not 1 to 8).

Further, running the above example you have provided with ``facets = [[1, 2], [2, 3], [3, 4], [4, 1], [5, 6], [6, 7], [7, 8], [8, 5]]`` in version ``1.0.8``, I get ``IndexError: list index out of range`` as expected. I also get the same error when running with version ``1.0.0``.

The current docs for [creating geometry from a list of points](https://sectionproperties.readthedocs.io/en/latest/rst/geom_mesh.html#geometry-from-points-facets-holes-and-control-points) has a reference to [this](https://sectionproperties.readthedocs.io/en/latest/sphinx_gallery_examples/00-basic/03_custom.html#ref-ex-custom) example, which clearly shows the point indices start at 0 (zero).

I am unsure where you got the above example from with indices from 1 to 8 as I couldn't find it in the repository?

I hope this addresses your question, please let me know if you have any other queries :)

**Comment by MarcoV10** [comment]
Thank you Robbie, this addresses the question, not sure why I had the template with the serial in a different manner

Many thanks for your prompt response
