### ISSUE TITLE
Warping constant gamma multipled by E-Modulus?

### ISSUE THREAD

**Issue by MichaelBuehler** [robbievanleeuwen/section-properties#207]
I am wondering if the expression for Warping constant in section.py is correct:

```python
self.section_props.gamma = i_omega - q_omega**2 / self.section_props.ea - y_se * i_xomega + x_se * i_yomega
```

It looks like ``q_omega``, ``i_omega`` are getting multiplied by ``sectionProperties.ea``.		

Should it not get divided by ``self.section_props.ea``?

```python
self.section_props.gamma = (
   i_omega - q_omega**2 / self.section_props.ea - y_se * i_xomega + x_se * i_yomega ) / 
   self.section_props.e_eff
)
```

I did not test out this python implementation, but there is a C# translation where gamma gets by E-Modulus factor too high. 
Similar issues exist for Shear Areas and Torsional constant if material E-Modulus different than 1

**Comment by robbievanleeuwen** [comment]
Hi @MichaelBuehler, thanks for the message.

This consistent implementation is to enable composite material analysis. If no material properties are specified, the warping constant is returned unfactored. If material properties are defined then ``E. $\Gamma$`` (modulus weighted warping constant is returned). If, for whatever reason, you are only interested in the warping constant, then you can simply divide the output by ``E_eff`` as you've indicated. 

I would suggest reading the documentation [here](https://sectionproperties.readthedocs.io/en/latest/rst/post.html#how-material-properties-affect-results) and [here](https://sectionproperties.readthedocs.io/en/latest/rst/theory.html#warping-constant) to gain a deeper understanding of how *sectionproperties* deals with materials. The first link shows an example of transforming the output ``E.J`` to ``G.J``, which is a property quite often used in structural analysis.

Please le me know if you have any more queries on this, happy to help!

**Comment by robbievanleeuwen** [comment]
Hi @MichaelBuehler, wondering if this clarifies the issue for you? If so, I will close this issue.
