### ISSUE TITLE
Testing the Installation fails for test_sections

### ISSUE THREAD

**Issue by simo-11** [robbievanleeuwen/section-properties#216]
**Describe the bug**
Testing the Installation fails for test_sections due to missing files in python package and file referencing errors.
using \_\_file\_\_ instead of pathlib.Path.cwd()/... is one possible solution for referencing files in tests module.

**To Reproduce**
pytest --pyargs sectionproperties

**Expected behaviour**
Test would be run successfully

**Screenshots**
sectionproperties\tests\test_sections.py ......F.FFFF.....                                                                                                             [ 94%]
==================== FAILURES ====================
_____ test_geometry_from_dxf ___
    def test_geometry_from_dxf():
        section_holes_dxf = (
            pathlib.Path.cwd() / "sectionproperties" / "tests" / "section_holes.dxf"

**Desktop (please complete the following information):**
 - OS: Windows-10
 - Version 2.0.3

**Additional context**
section_holes.dxf and other non python files are missing from python package
![image](https://user-images.githubusercontent.com/1210784/170816205-994aa965-bc30-4bb3-b12a-7af602b03c18.png)
![image](https://user-images.githubusercontent.com/1210784/170816225-c4175d2a-4157-4b36-b7e4-f3a2d2b41bb9.png)

**Comment by robbievanleeuwen** [comment]
@simo-11 thanks for raising this! I can reproduce on my end as well.
