### ISSUE TITLE
Can't install on M1 Mac (problem in triangle library)

### ISSUE THREAD

**Issue by mfeif** [robbievanleeuwen/section-properties#218]
**Describe the bug**
sectionproperties cannot be installed on an M1 Mac because of [this bug in triangle](https://github.com/drufat/triangle/issues/62). It's on the C side of things, it seems.

I'm just wondering if anyone here has figured out a work-around or if there's a way to go back to the older mesh library (I saw the discussion over in "Discussions" about the port). Or maybe an older version of sectionproperties can be installed?

**To Reproduce**
Steps to reproduce the behaviour:
1. pip install sectionproperties
2. see failure message

**Desktop (please complete the following information):**
 - OS: MacOS on M1-pro
 - Version 12.3.1 (21E258)
 - Python: 3.10.2 installed via pyenv (compiled for M1)

**Additional context**

**Comment by robbievanleeuwen** [comment]
Hi @mfeif,

Sorry to hear you're having trouble installing ``triangle``. Have you tried running a virtual environment with either python 3.8 or 3.9?

In the meantime, you could try running an older version of *sectionproperties* as you've suggested. ``triangle`` was adopted in ``v2.x.x`` so you could run with ``v1.0.8`` which uses ``MeshPy``, you can find the docs for that version [here](https://sectionproperties.readthedocs.io/en/1.0.8/).

Hopefully the issue with ``triangle`` gets resolved soon!

**Comment by robbievanleeuwen** [comment]
Closed as not a *sectionproperties* issue.

**Comment by robbievanleeuwen** [comment]
@mfeif, if you're still around, `sectionproperties` v3.3.0 can be able to be installed on computers with Apple Silicon processors as we are now using [CyTriangle](https://github.com/m-clare/cytriangle).

**Comment by mfeif** [comment]
Amazing. Thank you for the heads-up!
