### ISSUE TITLE
meshpy is no longer supported?

### ISSUE THREAD

**Issue by BenjaminETaylor** [robbievanleeuwen/section-properties#22]
I'm having trouble installing meshpy on a linux mint machine with Python 3.6.9, and ultimately found [this closed issue](https://github.com/BerkeleyAutomation/meshpy/issues/6) on their github page. In there it says:

> Unfortunately, Python 3+ will not be supported for meshpy. @jeffmahler

Since this conflicts with section-properties' Python 3.5+ requirement, maybe consider switching to [triangle](https://pypi.org/project/triangle/#description) instead? It looks like it uses the same underlying mesh library.

**Comment by robbievanleeuwen** [comment]
Hi Benjamin,

As far as I know meshpy still works fine. Looks like you are looking at the wrong package - [this](https://github.com/inducer/meshpy) is the meshpy that is used by sectionproperties and that is on the python package index.

Robbie

**Comment by BenjaminETaylor** [comment]
Robbie,
Good catch. I did not realize I was looking at a different meshpy! However, I am still not able to install the pypi version of meshpy on my machine. Looks like it's due to a compiler incompatibility (although I don't know why, I have gcc 7.5.0 on my machine). The bigger problem is that this issue also prevents me from installing section-properties!
I looked into it more and I think the [triangle](https://pypi.org/project/triangle/) library does everything section-properties needs, and it installs without issue. I'm willing to give the conversion a shot myself. What are your thoughts? The triangle library has the following benefits:

- fewer end-user installation issues
- lighter weight dependency
- newer releases (latest release -> 04/24/2020)
- same underlying meshing algorithms

**Comment by robbievanleeuwen** [comment]
Hi Benjamin,

Happy to investigate this further as you're not the first person I've come across that has had meshpy installation issues. Everyone I talked to did eventually manage to resolve the issue, but it would be better if no one had problems!

I did initially look at the triangle and the deal breaker was that it didn't generate 2nd order elements (6 node triangles), only 3 nodes. I need these elements for my computation of the section properties so ended up going with meshpy instead. This is a feature of the original triangle written in C so if the developers of the python triangle library included this feature then a switch over to triangle would be more likely!

Robbie

**Comment by BenjaminETaylor** [comment]
Robbie,
I thought that was a deal breaker too, but when I tested it with the 'o2' flag (see original docs) it did create second order elements (6-node Tris). It's also able to handle the 'q' and 'a' flags which are two other options section-properties uses. I did not test the 'regions' functionality, and I didn't see anything about 'attributes'. But, I think you're using meshpy attributes mainly to keep track of material assignments? That's probably something that can be handled separately, yeah?
Let me know what you decide. I can help!

**Comment by robbievanleeuwen** [comment]
Thanks for the heads up! I'll have a little play around and see if it fits the bill :)

**Comment by smith120bh** [comment]
I saw this thread and wanted to just jump on to point out that meshpy is already just a Python shell over the C programs Triangle (for 2D) and TetGen (for 3D). Given that the Meshpy wrapper has an unrestricted license, you could always pull out the Python wrapper files relevant for triangle and just package them directly with section-properties? 

I did a similar edit for making use of Meshpy myself, since (a) I'm never using 3D meshes and (b) so that I could edit the wrapper to include the `S` parameter for triangle (for setting the maximum number of Steiner points - helps keep the mesh from going haywire with arbitrary shapes).
