### ISSUE TITLE
Geometries are reported as disjoint when adjacent and still connected

### ISSUE THREAD

**Issue by robbievanleeuwen** [robbievanleeuwen/section-properties#222]
Sorry @connorferster, just picked this up - I should have added more tests as you suggested, always my downfall 🤣 

See test added in fd80b05.

Once resolved I'm thinking of bumping the version to ``2.1.0`` as we've got some nice new visuals in the console printing and have had a few nice features added recently 👍

**Comment by robbievanleeuwen** [comment]
Hi @connorferster sorry just thought of one more edge case which I think this is missing. I really need to do a better job of thinking about this earlier!

Added a (hopefully) final test in 62a9244.

**Comment by connorferster** [comment]
Are these geometries connected at a point? I was expecting the updated implementation to work for any kind of "touching" of geometries.

**Comment by robbievanleeuwen** [comment]
![image](https://user-images.githubusercontent.com/18841910/172105496-792d2236-12f6-4311-952c-17f1a38fe7fb.png)

**Comment by robbievanleeuwen** [comment]
Looking at ``check_geometry_disjoint()``:

- ``rect1`` intersects with ``rect2``, all good ✔️ 
- ``rect1`` intersects with ``rect3``, all good ✔️ 
- ``rect2`` does not intersect with ``rect3``, ❌ - this results in the function thinking the geometry is disjoint.

**Comment by connorferster** [comment]
@robbievanleeuwen Thanks for investigating that! I had this scenario in mind during development and am surprised by the result. Will investigate further...

**Comment by robbievanleeuwen** [comment]
Closed with #225
