### ISSUE TITLE
Speed up by calculating shape functions once!

### ISSUE THREAD

**Issue by robbievanleeuwen** [robbievanleeuwen/section-properties#231]
We are constantly recalculating shape functions and associated values throughout a geometric & warping analysis. Would it be faster just to pre-calculate these on initialisation of the finite element and store them for use later?

**Comment by robbievanleeuwen** [comment]
Also add Tri3 elements and compare results!

**Comment by TLCFEM** [comment]
It is possible to make shape function related funtions as methods of element class. The result can be cached based on the input coordinates. I can make the changes if you do not mind?

**Comment by robbievanleeuwen** [comment]
Hi @TLCFEM, happy for you to put together a PR for review :rocket:
