### ISSUE TITLE
Export options to existing mesh file types (.obj, .ply, .stl etc)

### ISSUE THREAD

**Issue by arjundharma** [robbievanleeuwen/section-properties#249]
Hello, was wondering if you have any plans on adding export options for mesh files such as .obj, .ply, and .stl formats (used by other libraries like trimesh and pymesh). I know you currently export as a python dict and I've been looking into ways to parse them into those formats.

Thanks for putting together this library!

**Comment by robbievanleeuwen** [comment]
Hi @arjundharma, this isn't really the scope of *sectionproperties*. We use the library [triangle](https://github.com/drufat/triangle) to generate a mesh (this is what produces the dictionary) and *sectionproperties* steps in and uses this mesh for its cross-section analysis. 

So in short there aren't any plans to export mesh in different formats, however I would consider a PR if you are interested in adding this feature 🙌
