### ISSUE TITLE
Package a new release

### ISSUE THREAD

**Issue by DanShort12** [robbievanleeuwen/section-properties#25]
Hi Robbie,

First of all, thanks for the great utility - it's helped us get off the ground on a project with surprisingly little effort.

**Is your feature request related to a problem? Please describe.**
We are creating meshes of a set of systems with a pretty complex geometry, which means that even with some cleaning of our own we regularly hit the infinite loop reported in #15. Reason being, we have quite a few curves, which naturally introduce shorter facet lengths. Of course we can build from source (and currently are building from source) to work around that but it would be much more convenient if there was a packaged version that included this fix.

**Describe the solution you'd like**
Create a version 1.0.6 release and package in PyPI.

**Describe alternatives you've considered**
Build from source and maintenance on our side of installer scripts that allow a user to checkout the repo at 9d74737 and install into their environment.

**Additional context**
If you're not in a position to release in the short term, it would be helpful to know when you might intend to package your next release - I can see it's been nearly 11 months since the last package.

**Comment by robbievanleeuwen** [comment]
Hi Dan,

Just packaged the current master branch to 1.0.7 (had an issues with pypi with 1.0.6).

Thanks for the prompt - definitely needed updating!

Robbie
