### ISSUE TITLE
Some shapely imports need to be fixed for compatibility with shapely v2.0

### ISSUE THREAD

**Issue by connorferster** [robbievanleeuwen/section-properties#258]
**Describe the bug**
Shapely 2.0 has been released (!!!) Yay!

However it seems that this kind of import:

```python
import shapely

shapely.affinity.translate(geom, ...)
```
Needs to be replaced with this:

```python
from shapely import affinity

affinity.translate(geom, ...)
```

**To Reproduce**
Steps to reproduce the behaviour:
Run test suite with shapely 2.0 installed

**Additional context**
Have not checked this out extensively. Need to see what the extent is...

**Comment by robbievanleeuwen** [comment]
Thanks @connorferster, yes never got around to testing any of the shapely release candidates!

From memory the other thing that needs to be checked in the STRTree.

**Comment by robbievanleeuwen** [comment]
For now do you think it's worth pinning ``shapely<2.0`` until fixed?
