### ISSUE TITLE
Better mesh size control in triangle

### ISSUE THREAD

**Issue by robbievanleeuwen** [robbievanleeuwen/section-properties#259]
### Discussed in https://github.com/robbievanleeuwen/section-properties/discussions/257

<div type='discussions-op-text'>

<sup>Originally posted by **audunarn** December  2, 2022</sup>
Hi, I find that it is easier to control the mesh size in triangle by changing the max/min angle (in pre.py):

# generate mesh
if coarse:
    mesh = triangle.triangulate(tri, "pAo2")
else:
    mesh = triangle.triangulate(tri, "pq**30**Aao2")

I could add this functionality if you wish.</div>

**Comment by SoundsSerious** [comment]
I think this would really help with some of the segmentation fault issues #284 that I find will occur sometimes.

Would there be any advantages to trying a different meshing library?

**Comment by robbievanleeuwen** [comment]
Hi @SoundsSerious, there is a new library [cytriangle](https://github.com/m-clare/cytriangle) in development that looks promising - watch this space.

**Comment by SoundsSerious** [comment]
Yes that looks great, hopefully that would plug right into `sectionproperties`
