### ISSUE TITLE
Function Vx shear stress plot with incorrect title

### ISSUE THREAD

**Issue by Chivos** [robbievanleeuwen/section-properties#266]
Hi,

I noticed something weird at this line :
https://github.com/robbievanleeuwen/section-properties/blob/12763207b0981c9932cbe1b56914b84057ce3491/sectionproperties/analysis/section.py#L3632
In this function for plotting Vx shear stress, there is a title refering to the tension caused by bending.

I found this while trying to understand why I'm unable to give my own title on the plot for Vx shear in a 3x3 subplot...
Didn't find for now if it's my code or sectionproperties...

**Comment by Chivos** [comment]
Seems to be in conflict with line 3672

**Comment by robbievanleeuwen** [comment]
Hi @Chivos thanks for this, will merge the PR.
