### ISSUE TITLE
section.calculate_warping_properties(solver_type='cgs') fails due to NameError

### ISSUE THREAD

**Issue by simo-11** [robbievanleeuwen/section-properties#268]
**Describe the bug**
Calculation of warping properties fails when using solver_type='cgs'

**To Reproduce**
section.calculate_warping_properties(solver_type='cgs')

sectionproperties\analysis\section.py", line 402, in ilu_decomp
    (self.num_nodes, self.num_nodes), linalg.spilu(k).solve

NameError: name 'k' is not defined

**Additional context**
It seems that issue due partially made refactoring as assemble_torsion was modified to return only lagrangian version of k (k_lg) and no k at all.

Fixing
 * remove usage of k  and k_precond in calculate_warping_properties will be provided

**Comment by robbievanleeuwen** [comment]
Thanks for picking this up @simo-11. I have resolved this for the upcoming release, see [here](https://github.com/robbievanleeuwen/section-properties/blob/hypermodern/src/sectionproperties/analysis/section.py#L393).

Fixed by #277.
