### ISSUE TITLE
Mesh Segmentation Fault

### ISSUE THREAD

**Issue by SoundsSerious** [robbievanleeuwen/section-properties#284]
Thanks for putting together this wonderful library. Happily making lots of airfoil cross sections.

I am stumbling across a mostly infrequent `segmentation fault` that occurs depending on the underlying geometry. 

I see this issue has been discussed in #42 however it seems there isn't a good resolution except to "check the mesh" 

The `triangle` mesh  library that is used has a few issues that are related, two issues have happened 
https://github.com/drufat/triangle/issues/70
https://github.com/drufat/triangle/issues/2

It looks like two of these issues have popped up causal to a release Feb 1st
https://github.com/drufat/triangle/compare/v20200424...v20220202

**Comment by SoundsSerious** [comment]
Having some some trouble compiling previous versions of triangle so I can't provide any info on if the previous version works yet

**Comment by smith120bh** [comment]
I was experiencing random segfaults, that I pinned down to occurring when I had nodes that were very close to, but not exactly coincident with each other. 

I don't know if this might be specifically the case for you or not, but note that if you're creating a geometry from custom points, then you do NOT need to repeat your first point - shapely will automatically close your section for you. I was trying to repeat my first point, and I realised that floating point round-off error was resulting in me placing my end point ever so slightly separated from my start point. I fixed this by just dropping my end point and letting shapely close the section for me.

**Comment by SoundsSerious** [comment]
Yes that or something similar is highly likely for me since I'm working with thin-walled airfoils. I found rounding the corners for the aircraft spars (shapely holes) could be problematic as well although I would imagine that would make meshing easier!

I should say generally things are working, but it would be ideal to perhaps warn ahead of time when the shape is invalid.

![unnamed](https://github.com/robbievanleeuwen/section-properties/assets/10334493/9ccb969a-e9c0-46cc-8c0c-73b72f86b1ec)

**Comment by Hexus-One** [comment]
I've also been using the triangle library to calculate the centreline of roads and came across a similar issue (in my case it crashed silently with no error message). My problem space is similar - long, thin shapes - and I ended up resolving it by removing the rounding that was being performed on the polygon points and was thus creating a lot of colinear points.

See the example image below (mesh boundary in cyan with blue points)
![crash1](https://github.com/robbievanleeuwen/section-properties/assets/5473838/903750d3-23cf-48e6-8e95-aa280f9bee54)

**Comment by robbievanleeuwen** [comment]
@SoundsSerious as your research has shown you, this is a common issue that users have experienced with the `triangle` library. The advice from @smith120bh is typically what I recommend, I have also found that some users have unknowingly included duplicate points in their custom geometry which can also upset `triangle`.

If you have a problem geometry I am happy to look at your python file and assist with debugging, otherwise I will probably close this issue as it is not something that is specifically related to the code in `sectionproperties`.

**Comment by SoundsSerious** [comment]
@robbievanleeuwen completely agree this is something outside the scope of `sectionproperties`.  I will close the issue since theres nothing we can do about this directly.

To add a best practice, I am pre-computing my sections at the start of an analysis and controlling failure with a minimum wall thickness before a large optimization, this way if there is a failure I can catch it early and retry.

**Comment by robbievanleeuwen** [comment]
Hi all, just a follow up to this thread. I am implementing the option to specify a minimum angle to mesh generation and stumbled across this [page](https://www.cs.cmu.edu/~quake/triangle.q.html). Potentially specifying lower minimum angles may help with some of your mesh generation issues (note current hard-coded default is 30deg).

**Comment by smith120bh** [comment]
> I am implementing the option to specify a minimum angle to mesh generation

That makes a lot of sense, and I agree that probably would have a lot of value in preventing errors like this.

As another thought - regardless of the meshing engine that's used for creating a mesh, I could see value in section-properties checking the _quality_ of the mesh. I've done some of this in my own (proprietary) software, but if you think it'd be valuable, I could also PR something similar for section-properties. Measurements such as the ratio of largest to smallest element, the maximum skewness of an element, and the maximum aspect ratio of each element are probably reasonable indicators (I've used the suggested limits in [this article](https://www.simscale.com/knowledge-base/how-to-check-and-improve-mesh-quality/), for example)

**Comment by SoundsSerious** [comment]
I think the minimum angle specification could help alot! I wonder if we could expose the input to the underlying mesh generator with a `keyword dict`? That might allow others to optimize for their unique use case

**Comment by robbievanleeuwen** [comment]
Hi @SoundsSerious minimum mesh angle is a feature that has now been added to the `hypermodern` branch - I am aiming to merge this branch to `master` today and hopefully release `v3` - the docs for this feature are [here](https://sectionproperties--277.org.readthedocs.build/en/277/user_guide/meshing.html) for now, with an example [here](https://sectionproperties--277.org.readthedocs.build/en/277/examples/geometry/create_mesh.html#Modifying-the-Minimum-Angle).

@smith120bh that would be a great addition, currently some basic info (num nodes, num elements, num regions) is reported with `display_mesh_info()` (see [here](https://sectionproperties--277.org.readthedocs.build/en/277/user_guide/analysis.html#checking-mesh-quality)), but if you are interested you could expand the output of this method with those metrics!

**Comment by SoundsSerious** [comment]
Thanks! I'll take a look and familiarize myself with the code!
