### ISSUE TITLE
Calculate Frame Properties with SHS and specific dimensions errors

### ISSUE THREAD

**Issue by michaellisitsa** [robbievanleeuwen/section-properties#35]
**Describe the bug**
When entering a RHS cross section using the function section.Rhs(d, b, t, r_out, n_r), the creation of the mesh functions properly, however when calculating frame properties using function section.calculate_frame_properties(), specific dimensional combinations of d and b don't work.

For example, with below code. The values initiating this error seem random. For example, d=0.25 or 0.26 works, however, 0.22 or 0.23 doesn't work.

The exact same dimension combinations works with section.calculate_geometric_properties()

The error appears to suggest one of either self.section_props.ixx_c, i11_c or ixy_c within the cross-section.py file is a 'NoneType'.

**To Reproduce**

    import sectionproperties.pre.sections as sections
    from sectionproperties.analysis.cross_section import CrossSection
    geometry = sections.Rhs(d=0.23, b=0.25, t=0.02, r_out=2.5*0.02, n_r=8)
    mesh = geometry.create_mesh(mesh_sizes=[0.02**2])
    section = CrossSection(geometry, mesh)
    geometry.plot_geometry()
    (area, ixx, iyy, ixy, j, phi) = section.calculate_frame_properties()

**Expected behaviour**
Outputs results of the *calculate_frame_properties()* function
**Screenshots**
![image](https://user-images.githubusercontent.com/58811856/94143911-cff89f80-feb3-11ea-8cc7-f743463283dc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 1709
 - Browser [e.g. chrome using JupyterLab]
- Sectionproperties Version: 1.0.7

**Comment by robbievanleeuwen** [comment]
Hi @michaellisitsa,

Thanks for the pick-up spotted a small assignment error in the `frame_properties` function. Fixed with commit 2dbbff0.

Will incorporate this into the next release shortly.

Cheers,
Robbie
