### ISSUE TITLE
add an option

### ISSUE THREAD

**Issue by jiandong-qiao** [robbievanleeuwen/section-properties#360]
In reinforced concrete section, can you add an option: Do not subtract the area of steel in the concrete.Because, in the specification calculation formula, the area of the concrete part occupied by the steel bar does not need to be deducted.Thanks.

**Comment by robbievanleeuwen** [comment]
Hi @jiandong-qiao, thanks for your question. `sectionproperties` uses the finite element method to calculate cross-section properties and relies on generating a mesh. Unfortunately, the library we use to generate the mesh, [triangle](https://github.com/drufat/triangle), does not support elements stacked on top of one another. While it would be possible to create this geometry with the pre-processor, the meshing algorithm would end up subtracting the concrete area. As a result, this is not currently an option to be supported.

**Comment by jiandong-qiao** [comment]
> Hi @jiandong-qiao, thanks for your question. `sectionproperties` uses the finite element method to calculate cross-section properties and relies on generating a mesh. Unfortunately, the library we use to generate the mesh, [triangle](https://github.com/drufat/triangle), does not support elements stacked on top of one another. While it would be possible to create this geometry with the pre-processor, the meshing algorithm would just end up subtracting the concrete area. As a result, this is not currently an option that can be supported.

i see thanks
