### ISSUE TITLE
invalid imports in the documentation

### ISSUE THREAD

**Issue by BALOGHBence** [robbievanleeuwen/section-properties#361]
The examples in the documentation ofter point to invalid references. For instance, the following imports

```python
from sectionproperties.pre import Material
from sectionproperties.pre.library import i_section
from sectionproperties.analysis import Section
```

should be

```python
from sectionproperties.pre.pre import Material
from sectionproperties.pre.library.steel_sections import i_section
from sectionproperties.analysis.section import Section
```

These could be avoided by either populating the __init__.py files or correcting the examples in the docs.

At the 'Results' section of the User Guide, the reference to the function `plot_stress` is invalid.

![image](https://github.com/robbievanleeuwen/section-properties/assets/25981557/c226fde8-81e9-4e4c-9c5e-bf7894d7f30a)

**Comment by robbievanleeuwen** [comment]
Hi @BALOGHBence, are you getting any import errors? The ``__init__.py`` files already contain these references so they should work. This was introduced recently in [v3.0.0](https://github.com/robbievanleeuwen/section-properties/releases/tag/v3.0.0) to improve readability (see features).

I cannot find the invalid reference to plot stress, could you clarify this?

**Comment by BALOGHBence** [comment]
Hi. I think the problem here is that I used the package under Python 3.8. I can see now that version 3.0.0 is only from Python 3.9.
