### ISSUE TITLE
Return (fig, ax) required imminently for compatibility with Streamlit plotting

### ISSUE THREAD

**Issue by michaellisitsa** [robbievanleeuwen/section-properties#37]
I believe you've already solved this in #33 and related updates, however as it hasn't been published on PYPI, just bringing your attention to the fact that Streamilt, which is a library for generating web apps, will soon require any functions that use Matplotlib to return `fig`.

**How it works**
Streamlit doesn't display any Matplotlib figures unless you call `streamlit.pyplot(fig)`. If nothing is passed in, Streamlit has previously just run `plt.savefig()` and outputted which works with SectionProperties module. However, there is a deprecation warning for 1st December 2020 (although they are yet to remove it from the codebase) that advises this will no longer be allowed.

**How to replicate**
```python
import streamlit as st

# sectionproperties object setup not shown

geometry.plot_geometry()  # plot the geometry

st.pyplot() #Plot the cross section shape of the box girder

```

Warning given:
![image](https://user-images.githubusercontent.com/58811856/101270471-7c68d300-37cd-11eb-9e3f-cf4de9ef9623.png)

**Expected behaviour**
```python
fig, ax = geometry.plot_geometry()  # plot the geometry

st.pyplot(fig) #Plot the cross section shape of the box girder
```

At the moment I'm using the following workaround which works, however the figures don't always come our right (e.g. need to manually fix the aspect ratio etc.)
```python
fig,ax = plt.subplots()
geometry.plot_geometry(ax=ax)  # plot the geometry

st.pyplot(fig)
```

**Setup**
Streamlit 0.72
section properties 1.07

**Comment by robbievanleeuwen** [comment]
Hi @michaellisitsa,

Thanks for the heads up. Apologies for the delay - life has got in the way of things recently.

Version is now bumped to 1.0.8 which includes the plot changes and hopefully closes this issue!

Robbie
