### ISSUE TITLE
Python 3.12

### ISSUE THREAD

**Issue by robbievanleeuwen** [robbievanleeuwen/section-properties#401]
Support Python 3.12!

Currently awaiting `rhino3dm` for full integration.

**Comment by dpnova** [comment]
I notice `rhino3dm` is an optional dep - I'll get the team to try installing/using the lib without it cc @haiderali101

**Comment by robbievanleeuwen** [comment]
Hi @dpnova, `rhino3dm` is currently an optional dependency and will not be installed by running `pip install sectionproperties`. It will only be installed by running `pip install sectionproperties[rhino]`, more info [here](https://sectionproperties.readthedocs.io/en/stable/installation.html).

**Comment by dpnova** [comment]
> Hi @dpnova, `rhino3dm` is currently an optional dependency and will not be installed by running `pip install sectionproperties`. It will only be installed by running `pip install sectionproperties[rhino]`, more info [here](https://sectionproperties.readthedocs.io/en/stable/installation.html).

Circling back to this @robbievanleeuwen - I've been out of python land a bit so I'm not super familiar with newer tools like poetry etc.

when I run 

```
pip install pandas numpy matplotlib scikit-learn scipy \
    seaborn PyniteFEA sectionproperties \
    SimPy SymPy joypy PyCBA indeterminatebeam \
    fenics Topologicpy Eurocodepy \
    concreteproperties StructPy COMPAS pycalculix \
    BeamBending anastruct pysal topojson shapely handcalcs
```

I see this in the output just before rhino3dm starts building (long build):

```
Collecting rhino3dm (from rhino-shapley-interop>=0.0.4->sectionproperties)
  Downloading rhino3dm-8.4.0.tar.gz (66.0 MB)
```

I see in the pyproject.toml for sectionproperties that the dep is an optional, when using the rhino extra in poetry.

Curiously, when i run:

```
pip install sectionproperties 
```

it doesn't start building rhino3dm, what am I missing here? :D My guess is that one of the other deps is causing an upgrade of a transitive lib, which is making sectionproperties do something very odd?

**Comment by robbievanleeuwen** [comment]
Hi @dpnova, in previous versions of `sectionproperties`, `rhino-shapley-interop` (and thus `rhino3dm`) was not optional. Have you tried installing `sectionproperties` in a fresh virtual environment? It looks like you have some older versions cached in your environment.

If you're not contributing to the project, `poetry` shouldn't change anything for you - it's mainly used to manage the development dependencies and build the wheel.

**Comment by dpnova** [comment]
Thanks mate!
