### ISSUE TITLE
Version Attribute

### ISSUE THREAD

**Issue by Czarified** [robbievanleeuwen/section-properties#43]
**Is your feature request related to a problem? Please describe.**
Am I missing something, or is there no version attribute/variable that one can easily call for this library?

**Describe the solution you'd like**
```python
import sectionproperties as sp
print(f'SectionProperties Version: {sp.__version__}')
```
The above code will result, if a `__version__ = '1.0.8'` line is added to the overall init.py file (sectionproperties > init.py)

Additionally, your setup.py file and docs can reference this value, instead of manually updating them all for each release.

**Describe alternatives you've considered**
Some other python libraries use a version module. Not sure what the real purpose is of these, but I think a simple `__version__` attribute for the library will suffice for basic checks.

**Additional context**
The reason for this consideration is to provide a user with a way to document what version of the library was used when performing an analysis. For engineering analysis, I typically like to log all library versions at the top, just so I can be sure I know how to repeat my results. As we start looking at overhauls to pre-, post-, testing suites, and meshing algorithms, this could be even more useful, and the change seems minor to me with no drawbacks.

Your thoughts, robbie? It's a simple change, but I could put in a PR for you to review? I'm trying to learn all the shapely and testing stuff along with the great work connor's doing, and I just noticed this while setting up. :)

**Comment by Czarified** [comment]
For additional reference, this is how Shapely defines its version variable as well, but they actually do something a bit more fancy with their setup.py and docs references. I'm too inexperienced to understand immediately what's going on.

**Comment by robbievanleeuwen** [comment]
Hi @Czarified,

Happy to add a version attribute to the package and agree it will make it easy to update version numbering! Engineering motivation makes sense as well.

Happy for you to put in a PR and I will merge.

Cheers!
Robbie

**Comment by Czarified** [comment]
I'll throw something together tonight.

While I'm working in the setup.py for the version: what's the reason for for requiring SciPy <= 1.5? Did some of the solvers used in the plastic analysis get dropped after that version? I have 1.5.2 and geometric/elastic analysis seems to be working.

**Comment by robbievanleeuwen** [comment]
The issue is with SciPy 1.6 and greater, 1.5 series is fine hence the <= 1.5.

SciPy >= 1.6 requires Python >= 3.7 and I'm still allowing Python 3.6 so the quick fix was to enforce <= 1.5.

In the future I'll probably axe python 3.6 and remove the SciPy requirement.

**Comment by Czarified** [comment]
Ahh that seems to make sense. I try and stay up-to-date on my Python version, and I love the dataclasses and type hints of 3.7! I'm not worried about that, it just pops up as a pip conflict if another library calls SciPy >=1.5.1. Anyways, it's documented here, now, so people can hopefully search the repo and see why they may be getting a superfluous error.


#44 Addresses this issue.

**Comment by Spectre5** [comment]
Should the requirement instead be <1.6?  Since version above 1.5 will work such as 1.5.1.  Also, wouldn't a python version 3.6 installation just skip installing scipy 1.6 or greater since it isn't compatible.

**Comment by robbievanleeuwen** [comment]
Yes I meant to put the <= 1.5.* in the code which is the same as <1.6 but missed this! Will amend.

The installation fails if you are using python 3.6 (in fact was picked up by Travis CI).
