### ISSUE TITLE
Add r_in argument for rectangular_hollow_section

### ISSUE THREAD

**Issue by nelbs** [robbievanleeuwen/section-properties#492]
- [x] I have searched the [issues](https://github.com/robbievanleeuwen/section-properties/issues)
      of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://sectionproperties.readthedocs.io/) and
      believe that my question is not already covered.

## Feature Request

At the moment, the inner radius of a rectangular hollow section is calculated by subtracting the thickness (t) from the outer radius (r_out). This works well for cold-formed profiles, but it is not correrct for hot-rolled profiles; see the attached screenshot from the [Dlubal ](https://www.dlubal.com/en/cross-section-properties/)website.

Therefore, I want to do a request for adding an (optional) argument for the inner radius r_in"

![afbeelding](https://github.com/user-attachments/assets/87cec700-82db-4781-b120-a0c0281a7428)

**Comment by robbievanleeuwen** [comment]
Hi @nelbs, thanks for raising this. I'll add this feature when I next get some time off :)

**Comment by nelbs** [comment]
Thanks!

**Comment by robbievanleeuwen** [comment]
@nelbs, had a bit of time tonight and is a simple change - do you want to checkout #493 and see if this works as expected?
