### ISSUE TITLE
Add inbuilt option for tapered flange beams, & tapered flange channels

### ISSUE THREAD

**Issue by Agent6-6-6** [robbievanleeuwen/section-properties#7]
**Describe the solution you'd like**
Add a feature to generate properties for tapered flange beams and tapered flange channels. Often these are older sections, which are harder to source printed section properties for, so would seem like a useful addition to the capabilities of your programme.

Older beams often seem to be defined in the following manner:-
root radii
flange radii
flange angle
flange thickness at midpoint
![image](https://user-images.githubusercontent.com/36808164/56931427-18cbed80-6b34-11e9-835e-f9dcababa42a.png)
or similarly for channels:-
![image](https://user-images.githubusercontent.com/36808164/56931520-68121e00-6b34-11e9-88d0-9b8e93ac4bab.png)
taken from 
[Dorman Long 1906 Handbook.pdf](https://github.com/robbievanleeuwen/section-properties/files/3129420/Dorman.Long.1906.Handbook.pdf)

Though I note the US AISC S Shapes and tapered channel shapes are defined slightly differently (and not too clear to me what the intended flange angle and radii are!):-
![image](https://user-images.githubusercontent.com/36808164/56932107-8ed15400-6b36-11e9-8713-b79231a1f961.png)
![image](https://user-images.githubusercontent.com/36808164/56932175-c6400080-6b36-11e9-9735-b8b96db7dbec.png)

**Comment by robbievanleeuwen** [comment]
Actions:

- Implement TFB and TFC as per the British definition

**Comment by robbievanleeuwen** [comment]
Implemented in 8e35ec5.
