### ISSUE TITLE
Internal Volume Of Hollow Section

### ISSUE THREAD

**Issue by SoundsSerious** [robbievanleeuwen/section-properties#72]
It would be great to have a way to refer to the internal area of a hollow section, for things like heat / fluid flow, or buoyancy.

I've played around with a qhull on the mesh points, using shapely properties but for very thing sections nothing is reliable after an hour or so of play.

I think the best solution would be for the handful of hollow cross sections in the primitives in this library to define the 'holes' parameter of the meshpy interface, and then the areas could be returned with the same resolution as the physical mesh would. 

BTW this library is integrating very nicely with the fea solver at https://github.com/JWock82/PyNite :)

**Comment by normanrichardson** [comment]
I believe this may be addressed in the [Shapely preprocessor PR](https://github.com/robbievanleeuwen/section-properties/pull/66) (@connorferster). In my understanding this PR will mean that the geometry can be represented as a shapley object. This could then be queried for other geometric properties, such as the internal area of a shapes holes. 

For a shapely polygon (with holes) I was able to find the area of its holes by asking for its interiors coordinates, then using the coordinates to construct polygons of the hole and get its area.

**Comment by Czarified** [comment]
Yes, this would be handled with Shapely. If you're building your own custom section, you can just all the area of the piece you subtracted out. If you're using a built-in section from sectionproperties, you can use the `geom` attribute to get the Shapely polygon, then perform a bit of manipulation to get all the internal areas:

```python
from shapely.geometry import Polygon, box, Point
# Base box
a = box(0.0, 0.0, 5.0, 5.0)
# A smaller box we will subtract, forming a hole
b = box(1.0, 1.0, 2.5, 2.5)
print(f'The rectangular hole area is {b.area:.2f}')
# A circle we will subtract, forming a hole
c = Point(3.5 , 3.5).buffer(1)
print(f'The circular hole area is {c.area:.2f}')
d = a - b - c
# List comprehension to get a list of hole areas
holes = [Polygon(hole).area for hole in d.interiors]
print(holes)
print('Areas in the list above should match with print statements from before')
# Sum this list to get the total hole area, if desired
total_open_area = sum(holes)
```

**Comment by Czarified** [comment]
Note that the Shapely PR linked above is still unreleased. I'm not exactly sure how to do this with the current version.

**Comment by SoundsSerious** [comment]
Hey ok seeing that other PR out for the shapely pre-processor.

I considered shapely, but my issue was taking the discrete points and turning those into a shape, determining interior points is a ML problem i think this way.

If i'm understanding you switching all your primitives to shapely would allow for direct / faster property calculation, like area and thus you can subtract areas? That would totally work for my use case, shapely is a great library!

**Comment by SoundsSerious** [comment]
Not sure if this is related, but one pain point for me right now is the meshing time with thin sections, this isn't really unexpected, but maybe there could be a different mesh procedure that was faster for thin sections. Right now it would be difficult to know where a thin section would be but with shapely that would become more apparent!

**Comment by Czarified** [comment]
One thing you can do to speed that up is setting different regions, and specifying larger mesh sizes where you can. You really only need 2 elements thru the thickness (they're quadratic elements). Even that size may be miniscule for other parts of your section. If you're cranking mesh size down on the whole section, just to get a really refined mesh on a thin wall, then it will always take a while regardless of meshing algorithm. There's just a lot of elements in that case.

**Comment by normanrichardson** [comment]
One method to handle this for now is to use the information in the Geometry Class and convert it into shapely polygons. I used the facets, and points to build shapely polygons from the sectionproperty geometry. Then I used the hole points to determine which polygons are holes using the distance between the polygon and the hole points (there are more general methods to do this). I have not tested this on more general shapes or MergedSection etc.
```python
from shapely.geometry import Polygon, Point
import sectionproperties.pre.sections as sections
import numpy as np

# create a 150x100x6 RHS
rhs = sections.Rhs(d=150, b=100, t=6, r_out=15, n_r=8)

# Generator that yields pairs of consecutive facets (the 1 and 0 pair)
gen_facet_pairs = ( (rhs.facets[ii][1],rhs.facets[ii+1][0]) for ii in range(len(rhs.facets)-1))

# Now look for consecutive facets that are not the same 
# i.e this means a new polygon at that index
# Make a list of facet index of where these occur.
# Call this the "facet discontinuity"
polygon_idxs = [0]
for idx, facet_pairs in enumerate(gen_facet_pairs):
    if facet_pairs[0] != facet_pairs[1]: polygon_idxs.append(idx)
polygon_idxs.append(len(rhs.facets))

# Generator that yields the indexes of the start and end of the facet discontinuity.
# used to slice the facets list
gen_ploy_slice_idx = ( (polygon_idxs[ii], polygon_idxs[ii+1]) for ii in range(len(polygon_idxs)-1) )

# Retrience the polygons from the points and the facet discontinuities.
# not all the polygons are holes, one is the "perimeter" polygon
trial_holes = []
for poly_splice in gen_ploy_slice_idx:
    ploy_idx = rhs.facets[poly_splice[0]:poly_splice[1]]
    gen_poly_points = (rhs.points[ii[0]] for ii in  ploy_idx)
    trial_holes.append(Polygon(gen_poly_points))

# Determine which of the trial polygons represent holes
# this is done by using the distance between the hole points and the
# trial polygon boundaries.
# A more general method may be to use the shapely contains method
holes = []
for hole in rhs.holes:
    hole_p = Point(hole)
    dist = [ hole_p.distance(trial_hole.boundary) for trial_hole in trial_holes]
    holes.append(trial_holes[np.argmin(dist)])

[print(hole.area) for hole in holes]
```

> If i'm understanding you switching all your primitives to shapely would allow for direct / faster property calculation, like area and thus you can subtract areas?

I'm not sure what the motivation is exactly. However, I see it as an improvement as it makes the geometry more queryable. Thus, a lot of the niche section properties (like this issue in my opinion) can be answered easily as [demonstrated](https://github.com/robbievanleeuwen/section-properties/issues/72#issuecomment-854830509) by @Czarified. Ultimately, this helps keep the package "simple".

**Comment by Czarified** [comment]
@normanrichardson That's a pretty neat snippet of code! I'm gonna have to try that one out!

I can add a little bit more motivation for the switch. It's easier to create custom geometry for weird sections, including a DXF import feature. This was something requested and planned for a while, but it was complicated to convert into the older points/facets/control points setup (I think. I never attempted it). Additionally, with this switch, the library is using a standard python tool for geometry, with excellent documentation. And finally, with this refactor Connor is also cleaning up a lot of the code to be even more pythonic and maintainable. It should result in a better product, that will last longer, and be more easily updated if/when necessary. 😄

**Comment by connorferster** [comment]
Hi all!

I am working on it this weekend. It’s very close to finished.

I want to get this live!

**Comment by SoundsSerious** [comment]
@normanrichardson thanks for that example! I didn't realize there was a way to break down the points into groups!

I think that'll work :)

**Comment by normanrichardson** [comment]
I realized I made a good number of mistakes [above](https://github.com/robbievanleeuwen/section-properties/issues/72#issuecomment-855169597), mainly with the generator that does the slicing. So things are an index or so off. I decided to fix that error and make a function that can convert a sectionproperty geometry into a shapely polygon. It can be found [here](https://gist.github.com/normanrichardson/b05b02941d28aba91d4350e93ab7be8d).

**Comment by SoundsSerious** [comment]
Wow that is great! Seems like the Shapley progress is really turning out great!

**Comment by Czarified** [comment]
@SoundsSerious Could you close this issue? Were you waiting on some additional information?

**Comment by SoundsSerious** [comment]
@Czarified sure, yea i'm good on this issue
