### ISSUE TITLE
Torsion constant when using materials

### ISSUE THREAD

**Issue by ccaprani** [robbievanleeuwen/section-properties#76]
More of an FYI in advance of v2.0: when using two materials in a cross section, `display_results` shows the torsion constant as 
> G.J = xxx

the reported quantity is (in fact) E * J, which is consistent with the elastic modulus weighting of other composite cross section properties, but the use of "GJ" may be misleading. So the torsion constant should be found like `section.get_j()/precast.elastic_modulus` if the `precast` concrete is your reference material.

More broadly, since the `Material` class is not 'smart' a little hack is to just use `E = 1` for your reference material and `E = modular_ratio` for the secondary material (the Poisson's ratios should still be correct though for shear-related properties).

**Comment by robbievanleeuwen** [comment]
Hi Colin,

I need to do a bit of digging to confirm (remember!) what is going on here. My recollection was that I was converting the stored E.J to G.J when printing the results (see below line 197 in post.py):

`j / (2 * (1 + cross_section.section_props.nu_eff)`

However, for the user this isn't very clear, especially becuase if they were to call `get_j()` they would get E.J and may expect G.J as this is what is printed with `display_results()`. This issues ties into #53 and #6 which I need to address as it has been causing some people some issues!

I will test what is going on here in a simple case and get back to you!

Robbie

**Comment by robbievanleeuwen** [comment]
Updated in #120.
