### ISSUE TITLE
Custom Section reference point

### ISSUE THREAD

**Issue by someparsa** [robbievanleeuwen/section-properties#77]
Thank you for this amazing package. I am not sure whether this is seen in the calculations and an option exists for in the API or not. But this is a case I have faced and results in irregular values for second moments and shear point coordinates.

Normally we introduce the points on the boundary of a Custom Section using some coordinates. The origin of the coordinate system may not be located on the center of the gravity or rigidity of the cross section (CR). For instance, the (0,0) may be located on the far left point of the cross section. This causes the second moment values to be far higher than those calculated while the origin of the system is considered to be on the CR of the cross section.

This may not be a huge problem when we are doing FEM analysis but in engineering control problems, this is very important specifically when we are using the API to check cross section with the specifications of a standard. We need most of the cross section properties to be calculated while the (0,0) and origin of the coordinate system is set to be on the centroid of the cross section and I am afraid I can not find any relevant option or API code to do so.

Would you mind; if such an option exists please let me know and if it is not seen, some options probably be added to the API to make the package more usable by such engineers?

Thank you

**Comment by someparsa** [comment]
Reading the API documentations, it seems there are two options _c and _g for centroidal and global coordinates. So the problem described above seems to be solved. What about calculations about an arbitrary point P(x_0, y_0)? Like, Ixx_P.

**Comment by Czarified** [comment]
Hi someparsa! I think to get what you want, you _could_ shift your geometry around, such that the global axis is located at your desired coordinates.

There are 3 methods for calculating 2nd moments of area on a section: `get_ig()`, `get_ic()`, and `get_ip()`. They calculate the second moments of area about the global axis as modeled, the centroidal axis, and the principal axis.

To shift the section, you can use the `Geometry.shift_section()` method. I would actually recommend just creating new instances of shifted geometry, instead of trying to manipulate the same one. That method uses the "shift" class attribute, so you'd have to overwrite it if you wanted to manipulate the same section repeatedly.

I'm not sure if any of this helps or not, but from what I've seen, there is currently no implementation to calculate 2nd moments of area about an arbitrary point.

**Comment by someparsa** [comment]
Hi Benjamin, thank you. I think your comments on shifting the objects should work. I can shift the whole section to the desired point (for instance on a neighborhood of the center of rigidity) and then run the calculations. I should test this in my own codes.
By the way, I investigated the documentation and I can see the theoretical pages are under development. If we had a more clear view on the background theories, I would code and propose something for the package to include the idea of an arbitrary point. A new feature which will be consistent with the theories they have used and the codes and modules which are developed.
Let's wait and see what newer upgrades bring up for this wonderful package.

**Comment by someparsa** [comment]
Hi Benjamin, I checked the shift option you proposed. It only shifts the whole property. For instance we have a steel plate and we want to relocate it to somewhere on the flange. That option helps us. What we are discussing is a shift to the origin of the calculations to a desired point.

BTW, it seems there is an option here but I did not succeed to use it. I investigated the source but did not understand about its usage. Also I could not find a sample on it.

https://sectionproperties.readthedocs.io/en/latest/rst/api.html?highlight=calculate_centroidal_properties#sectionproperties.analysis.cross_section.SectionProperties.calculate_centroidal_properties

**Comment by Czarified** [comment]
Okay, so if you _really_ wanted to dig in and commit a new PR, [here's the theory from Robbie's blog](https://robbievanleeuwen.github.io/finite%20element%20analysis/calculating-section-properties-part1/), also see [Finite Element Preliminaries](https://robbievanleeuwen.github.io/finite%20element%20analysis/finite-element-preliminaries/). I think one could add a function to calculate these properties, but it's not currently implemented.

For reference, here's the docs page for the relevant element function:
https://sectionproperties.readthedocs.io/en/latest/_modules/sectionproperties/analysis/fea.html#Tri6.geometric_properties


Robbie or Connor, please correct me here if I'm wrong. Also, we _might_ want to copy over Robbie's blog posts into the official docs. I can put a PR together for that after we get v2.0.0 sorted with the massive PR's currently out.

**Comment by someparsa** [comment]
Thank you. Do you possibly have any comments regarding the usage of the link I included in my post? I think that would solve all these issues and seems it is seen in the package. Although I wonder whether it is included in warping cases or not.

**Comment by ccaprani** [comment]
The section properties must be calculated with respect to a coordinate system. You can see this in Robbie's blog referenced above, or the function `geometric_properties()` of `fea.py`. The point is that any implementation to obtain the section properties will only ever shift the coordinates from the original to the new coords, and then recalculate. So the user can just use the `Geometry.shift_section()` as noted above. There is nothing additional required in the package. 

It's worth noting that some properties (e.g. area, Ixx_c, etc) are invariant with respect to a coordinate transformation, and others amendable to simple calculation from the results already yielded (e.g. using the [parallel axis theorem](http://www.wikiengineer.com/Structural/ParallelAxisTheorem)), so not all use cases will require a costly FE re-computation.

**Comment by someparsa** [comment]
Thank you ccaprani and benjamin for all your informative comments and guides. As you describe, that shift function seems to be sufficient for this issue. Many thanks for this amazing package, I mark this issue to be closed.
