### ISSUE TITLE
Add output for external perimeter of section & surface area/m

### ISSUE THREAD

**Issue by Agent6-6-6** [robbievanleeuwen/section-properties#8]
**Describe the solution you'd like**
Would it be hard for any of the predefined sections to output the external perimeter length (sometimes called profile length in section tables) & surface area/m also? I'm guessing you already have a list of all the nodes making up the overall perimeter outline, and adding up the length of the lines connecting these nodes might be possible?

Why? For design these are used for fire capacity calculations where you need the Hp/A (heated perimeter over area ratio) and in general terms also for paint coverage comparisons between sections comparing surface area to be coated / linear length between varying sections (i.e. might be cheaper to use a thicker/smaller section of the same weight with less paint rather than larger lighter gauge section with more paint due to larger surface area).

**Additional context**
Many thanks for considering any of these additions!

**Comment by robbievanleeuwen** [comment]
Should be relatively easy to do - I will only output perimeter as surface area/m is a trivial calculation given the perimeter.

**Comment by robbievanleeuwen** [comment]
Incorporated in b93eb04.
