### ISSUE TITLE
v2 sectionproperties logo

### ISSUE THREAD

**Issue by robbievanleeuwen** [robbievanleeuwen/section-properties#88]
New v2 logo in sectionproperties has three red dots and white space above, see below screenshot:

<img width="775" alt="Screen Shot 2021-09-23 at 12 44 27 pm" src="https://user-images.githubusercontent.com/18841910/134447719-752fad9c-de3f-4ed3-be55-287910e6e7d1.png">

I'm guessing the white space was added for appropriate github repo logo requirements(?), but looks a bit funny on the home page of the docs? Maybe a different image file could be used for the docs homepage?

I know, really focussing on the big issues...

**Comment by robbievanleeuwen** [comment]
Further, there is transparency above the logo which doesn't work so well with backgrounds that aren't white (e.g. default rtd theme or if dark mode is activated).

<img width="882" alt="Screen Shot 2021-09-23 at 12 49 35 pm" src="https://user-images.githubusercontent.com/18841910/134448084-120967fb-e7f0-425a-a0bf-0a1a210f790a.png">

**Comment by connorferster** [comment]
Ack, I obviously did a poor job of generating the PNG: I actually fussed pretty hard on trying to get it of decent quality but I don’t think I was doing it properly.

**Comment by connorferster** [comment]
Will try again and let you know if I find it getting broken somewhere in the process

**Comment by robbievanleeuwen** [comment]
Fixed with #135
