### ISSUE TITLE
Legend not working in v2

### ISSUE THREAD

**Issue by robbievanleeuwen** [robbievanleeuwen/section-properties#97]
**Describe the bug**
Plotting the mesh with materials doesn't show the legend. Also the material colour is not displaying as expected.

**To Reproduce**
Code example from 'Advanced Geometry'

```python
import sectionproperties.pre.sections as sections
import sectionproperties.analysis.cross_section as cross_section
from sectionproperties.pre.pre import Material

i_sec1 = sections.i_section(d=250, b=150, t_f=13, t_w=10, r=12, n_r=12)
i_sec2 = i_sec1.rotate_section(45)

mat1 = Material("Material_1", 200e3, 0.3, 400, "green")
mat2 = Material("Material_2", 150e3, 0.2, 200, "red")  # Just some differing properties

i_sec1.material = mat1
i_sec2.material = mat2

cut_2_from_1 = (i_sec1 - i_sec2) # locates intersection nodes
sec_1_nodes_added = cut_2_from_1 | i_sec1

analysis_geom = (i_sec2 - i_sec1) + sec_1_nodes_added

analysis_geom.create_mesh([10])
analysis_sec = cross_section.Section(analysis_geom)
analysis_sec.plot_mesh()
```

Produces plot below:
<img width="519" alt="Screen Shot 2021-09-25 at 11 09 26 pm" src="https://user-images.githubusercontent.com/18841910/134772796-e80f2211-cafa-4a92-9c1b-342a06997667.png">

**Expected behaviour**
Material one to be green, with a legend displayed.

**Additional context**
Possibly also related to #94.

**Comment by connorferster** [comment]
Thanks @robbievanleeuwen, I have seen this bug before but thought I fixed it. Will investigate.
