### ISSUE TITLE
Control point rotation does not match section rotation (v2)

### ISSUE THREAD

**Issue by normanrichardson** [robbievanleeuwen/section-properties#99]
**Describe the bug**

There is an issue with [`Geometry.rotate_section`](https://github.com/robbievanleeuwen/section-properties/blob/b775277c4f438ff2b4def30c27115c37d36731d5/sectionproperties/pre/sections.py#L430) where under the default parameters the control point is rotated differently from the section. If `rot_point` is 'center' then the section is rotated about the center of the bounding box and the control point is rotated about the section's centroid. In general, this results in an unexpected behavior.

This only applies to geometries that have an `assigned_control_point`.
geometries that do not have an `assigned_control_point` regenerate a control point after the rotation operation (via shapely representitive_point).

**To Reproduce**

```python
import sectionproperties.pre.sections as sections
import matplotlib.pyplot as plt

a = 1
b = 2
t = 0.1

points = [[-t/2, -2*a], [t/2, -2*a], [t/2, -t/2], [a, -t/2], [a, t/2],
          [-t/2, t/2]]
facets = [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 0]]
holes = []
control_points = [0, 0]

geometry = sections.Geometry.from_points(points, facets, holes, control_points)

fig, (ax1,ax2) = plt.subplots(2)
geometry.plot_geometry(ax = ax1)
geometry = geometry.rotate_section(angle=30)
geometry.plot_geometry(ax=ax2)
plt.show()
```
<div align='center'>

<img src="https://user-images.githubusercontent.com/14271499/134793355-59518476-a197-4d19-9cbc-42cc96cb1c5d.png" width="358" height="365" />

</div>

**Expected behavior**

That the control point undergoes the same transformation as the section.

**Comment by connorferster** [comment]
@normanrichardson Thanks for that. Will tackle this. I am also looking at the rotated shape and it seems odd to me, like it's also being rotated out of plane. Will look into this also.

**Comment by normanrichardson** [comment]
@connorferster no worries, there is an attached PR #100. I did not see any out of plane rotations, but I did not check this

**Comment by connorferster** [comment]
Merged!
